### ISSUE TITLE
Sort proposals on /Governance by enactment newest - oldest

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#1002]
So that the proposals with the oldest enactment data appear at the bottom of the list. and ones furthest into future appear at the top.

at the moment a closed proposal appears at the top of the list.

In the future the page will have sort and filter functions

**Comment by cpuja84** [comment]
This was tested and signed off on Stagnet 1 (currently known as Staging). Now all the proposals are sorted according to enactment date with newest to oldest

<img width="1440" alt="Screenshot 2021-12-08 at 17 10 49" src="https://user-images.githubusercontent.com/69709857/145252857-9ec6a40c-15b5-4859-9932-597c17282723.png">
