### ISSUE TITLE
Proposal details. Change tense for closed proposals.

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#1003]
If the vote closed is in the past

- [x] closes on -> closed on
☝️ on both listing and details page

under the "Votes" heading: Vote status: [e.g. Participation not met]. [days left to vote]
- [x] Change to "Vote closed. Failed due to..." [x days ago] 
- [x] or Vote passed [x days ago]
- [x] and if the status is waitingfornodes "Vote passed [x days ago] subject to further actions"

**Comment by cpuja84** [comment]
The changes of wordings for update network governance proposal were verified on Staging / Stagnet1 as part of QA'ing this ticket. 

<img width="1440" alt="Screenshot 2021-12-08 at 17 10 49" src="https://user-images.githubusercontent.com/69709857/145254065-18a46740-7fda-4045-975a-0cf9217c2bcf.png">

<img width="920" alt="Screenshot 2021-12-08 at 17 18 51" src="https://user-images.githubusercontent.com/69709857/145254029-e3554971-85b1-4f1d-9f73-fb318b280af3.png">

<img width="973" alt="Screenshot 2021-12-08 at 17 19 34" src="https://user-images.githubusercontent.com/69709857/145254047-79414033-a94a-4e13-8471-8ea09cfc8233.png">
