### ISSUE TITLE
Adjust width for contract addresses

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/token-frontend#1004]
Right now, at its widest, the last number of the address just hangs by itself. Can the width be adjusted so that there isn't one number hanging out on its own for each of these addresses?
<img width="824" alt="Screenshot 2021-11-30 at 15 13 36" src="https://user-images.githubusercontent.com/62548908/144077745-76180cf0-2c05-41fb-a6aa-7a5461934487.png">

**Comment by cpuja84** [comment]
This work has been done 

![Screenshot 2021-12-01 at 16 27 58](https://user-images.githubusercontent.com/69709857/144273410-37c9ca91-4560-488f-97f8-00cd4dcbee28.png)

![Screenshot 2021-12-01 at 16 27 38](https://user-images.githubusercontent.com/69709857/144273420-b69b8f98-5b93-41c3-843e-d776822e04a3.png)
