### ISSUE TITLE
Bug: Rewards page - 422 error 

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/token-frontend#1006]
## Describe the bug

I have no tokens. Clicked on Rewards and it took a while to load, and then I got a 422 error. 

## Environment

Staging

## To Reproduce

1. Go to https://deploy-preview-989--token-vega-xyz.netlify.app/rewards
2. Click on Rewards
3. See error

## Expected behavior

Not an error :)

## Screenshots

<img width="1259" alt="Screenshot 2021-11-30 at 16 14 10" src="https://user-images.githubusercontent.com/62548908/144086133-82b05ae8-58a1-43b6-bfe1-cef52e91e423.png">
<img width="936" alt="Screenshot 2021-11-30 at 16 09 49" src="https://user-images.githubusercontent.com/62548908/144086153-e725f156-9408-40e5-95c2-5e6b8f445ada.png">

## Your browser information:

https://www.whatsmybrowser.org/b/BOEIT

**Comment by dexturr** [comment]
Devnet schema is different to mainnet/stagnet/testnet.

This will be a fix required for later.

**Comment by cpuja84** [comment]
Rewards works on Staging for me now
@candida-d - Can you quickly have a go at it as I don't have an account with no tokens on them. Thanks.

**Comment by candida-d** [comment]
@cpuja84 I tried staging in incognito and it looks good to me!
