### ISSUE TITLE
Tranche label font changes when you click on it 

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/token-frontend#1007]
When you click on the Tranche label, the font changes when it loads in the information. (staging) 
https://user-images.githubusercontent.com/62548908/144089065-09e8538d-9a84-446e-b5e7-6fd4a5520453.mov

**Comment by cpuja84** [comment]
@pgriscti - Has this changed pushed to Staging yet ? I can't see any difference in the font there yet.

**Comment by mattrussell36** [comment]
This should be on staging now @cpuja84

**Comment by cpuja84** [comment]
The bug fix works on Staging / Stagnet 1

<img width="946" alt="Screenshot 2021-12-08 at 18 23 53" src="https://user-images.githubusercontent.com/69709857/145262945-12c39cfa-66ac-4c46-adf9-e1d43952ccce.png">
