### ISSUE TITLE
Monospace styles (for eth address) applied to link to etherscan where it should not be.

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#1018]
There is a general rule that all public keys and hashes should use monospace fonts. however it appears to be applied here too. (In some cases this component shows an address)
<img width="479" alt="Screenshot 2021-12-01 at 10 46 19" src="https://user-images.githubusercontent.com/13255539/144231075-c2c7ab61-6d7e-403f-90ff-ed7d52e653bc.png">

**Comment by cpuja84** [comment]
This has been rectified in Staging, marking the ticket as done

![Screenshot 2021-12-07 at 13 56 21](https://user-images.githubusercontent.com/69709857/145042142-c4669599-c3e4-4130-87f3-64db4e818170.png)
