### ISSUE TITLE
Utillize webdriverio + chrome options for metamask interactions (SPIKE)

### ISSUE THREAD

**Issue by Ditmir-Vega** [vegaprotocol/token-frontend#1024]
https://www.guru99.com/chrome-options-desiredcapabilities.html

WebdriverIO framework supports chromedriver , chromedriver has various options with one of them being able to interact / install a  chrome extension. In this case we should look to utilize  this for metamask interactions

**Comment by dexturr** [comment]
Looks like this is not possible to run on github CI, as chromedriver does not support extensions.

Next step is to try out a HTTP provider :+1: to avoid MM all together
