### ISSUE TITLE
Fairground - hosted wallet toggles

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/token-frontend#1036]
# Bug report

## Describe the bug

The wallet URL field keeps the hosted wallet URL if you toggle between hosted and local. I can see how it would cause people some grief if they decide to click around and lose the local-host address, or not even realise they should have a different address there. 

NOTE: I can't now replicate this now, but I went to the fairground token site after not using it for a while and it had default filled to https://wallet.testnet.vega.xyz for local wallet, which is what caused me to raise this in the first place. Maybe a cookie thing?

## Environment

Fairground

## To Reproduce

1. Go to https://token.fairground.wtf/
2. Click on Connect to a Vega Wallet
3. Toggle Hosted Wallet on, and then off
4. See https://wallet.testnet.vega.xyz persist 

## Expected behavior

https://wallet.testnet.vega.xyz does not persist when toggling off 'hosted wallet'

## Screenshots

https://user-images.githubusercontent.com/62548908/144596292-7ec932bd-eed3-4bf2-ac8f-6c597a6e2f15.mov

**Comment by cpuja84** [comment]
I can't see the toggle button on Staging 
![Screenshot 2021-12-07 at 14 06 32](https://user-images.githubusercontent.com/69709857/145043794-4853015e-b7ef-48e4-a220-fb8a703f7c2c.png)

And checked it on Fairground too and attached video still holds true ie https://wallet.testnet.vega.xyz still persists when toggling off 'hosted wallet'

**Comment by campbellssource** [comment]
I suggest the action on this ticket is now to remove the switch (that only appears when you are on a site configured for fairground). Rationale: testing the real wallet is now more important than increasing participation with fairground. + users can still enter the wallet URL for fairground. + desktop wallet is close.

**Comment by gordsport** [comment]
Closing pending further feedback
