### ISSUE TITLE
SLP has ended, update page content and remove action

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#1040]
- [ ] Update copy
- [ ] Remove the deposit buttons
- [ ] remove withdraw without unsticking
- [ ] consider removing link at top of page (but see how many people are still in the pool)
- [ ] create and schedule a time

**Comment by cpuja84** [comment]
Tested this with @dexturr on token.vega.xyz and the changes look good so marking this ticket as done.
