### ISSUE TITLE
Dismissing wallet connect modal gets you stuck in loading state

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/token-frontend#1049]
Clicking outside the web3 modal to dismiss it gets you stuck in a loading state

**Comment by cpuja84** [comment]
Clicking outside the web3 modal to dismiss it works as expected.

**Comment by gordsport** [comment]
@cpuja84 - can you please re-test and close if no longer an issue?

**Comment by gordsport** [comment]
Closing - will reopen if reported again
