### ISSUE TITLE
Allow network switching on deploy previews of Token front end

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#1056]
I think this would help manual QA in cases where a PR is targeted for a specific version of core or environment.

I suggest our deploy previews are configured not for a specific network but with a flag that says network switching is on.
Then the token site renders a switch (but defaults to testnet)

**Comment by dexturr** [comment]
@campbellssource will this include mainnet?

**Comment by mattrussell36** [comment]
We have to consider the issue of GraphQL api compatibility. For example we couldn't switch between stag1 and stag2 as they have different api versions

**Comment by campbellssource** [comment]
Mainnet too?... yes preferably, but could be a follow up ticket.

**Comment by mattrussell36** [comment]
Blocking this for now as I think it might worth waiting for the latest data node stuff to reach mainnet. Otherwise we will have to manage different code branches for asset/assetId and party/partyId under the `Reward` type. Its up for debate though, we could code around it if deemed necessary

**Comment by campbellssource** [comment]
if this doesn't include mainnet we can use hard coded node values in database

**Comment by gordsport** [comment]
closing and to be considered when implementing:

- https://github.com/vegaprotocol/frontend-monorepo/issues/6
