### ISSUE TITLE
Github action that adds new issues to frontend project

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#1057]
We'd like all new issues to get added to the Frontend project for quick triage.

The project: https://github.com/orgs/vegaprotocol/projects/110/

example script for adding to project:
```
---
name: Auto Assign Issue to New Project

"on":
  issues:
    types: [opened]

jobs:
  add_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Add Issue to New Core Project Board
        env:
          GITHUB_TOKEN: ${{ secrets.GH_NEW_CARD_TO_PROJECT }}
          PROJECT_ID: "https://github.com/orgs/vegaprotocol/projects/110/"
          ISSUE_ID: ${{ github.event.issue.node_id }}
        run: |
          gh api graphql -f query='
            mutation($project:ID!, $issue:ID!) {
              addProjectNextItem(input: {projectId: $project, contentId: $issue}) {
                projectNextItem {
                  id
                }
              }
            }' -f project=$PROJECT_ID -f issue=$ISSUE_ID --jq '.data.addProjectNextItem.projectNextItem.id'
```

**Comment by gordsport** [comment]
The PROJECT_ID needs to be the node ID of the project for this query to run

To find this you can run 
`my_org="vegaprotocol"
    my_num=110
    gh api graphql -f query='
      query($organization: String! $number: Int!){
        organization(login: $organization){
          projectNext(number: $number) {
            id
          }
        }
      }' -f organization=$my_org -F number=$my_num`
      
The resulting Node_ID can then be added as a secret in github something like:
PROJECT_ID: ${{ secrets.FRONT_END_PROJECT_ID }}
