### ISSUE TITLE
Unable to cast vote on update network governance proposal

### ISSUE THREAD

**Issue by cpuja84** [vegaprotocol/token-frontend#1067]
I am unable to cast vote on update network governance proposal
I get the below something went wrong with the network every time.

<img width="1427" alt="Screenshot 2021-12-09 at 15 12 54" src="https://user-images.githubusercontent.com/69709857/145427882-dc992d0a-4ec0-45ae-a1cd-d044310cc093.png">

<img width="1430" alt="Screenshot 2021-12-09 at 15 12 41" src="https://user-images.githubusercontent.com/69709857/145427871-90ac2a10-dd52-4242-a017-cb1aa9418e9c.png">

**Comment by pgriscti** [comment]
Could this be that the wallet env is different from the app evn? It's working for me.
