### ISSUE TITLE
Header banner to warn when the network is young

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#1073]
<img width="1452" alt="Screenshot 2021-12-13 at 12 58 20" src="https://user-images.githubusercontent.com/13255539/145816825-e29011bc-3aee-41d6-bf51-06326fbdd5a1.png">

If the network is less than 900 blocks old then it could be that it hasn't restored from a check point yet. It could also be that the network is genuinely young.

If it is the former, and the network is mainnet than users may be distressed to see zero balance rather than the ones they expect.

This to show a message inform users that this might be the case

- [ ] Consider the copy (image is indicative)
- [ ] See if there is a better way than hard coding 900 blocks

**Comment by mattrussell36** [comment]
RE the copy. I think something briefer is better. How about just: "Chain restoration in progress...". I've asked the question to core as to how best to decided when to show the banner. 

UI is ready to go at [https://github.com/vegaprotocol/token-frontend/tree/feat/1073-banner](https://github.com/vegaprotocol/token-frontend/tree/feat/1073-banner)

**Comment by campbellssource** [comment]
@mattrussell36 to catch up with @pscott31

**Comment by campbellssource** [comment]
wait till the next checkpoint restore of testnet and check then

**Comment by campbellssource** [comment]
Re-opening this at @dexturr has discovered it won't work due to inconsistency of REST and GraphQL port

**Comment by gordsport** [comment]
Closing as this will be on @campbellssource todo list
