### ISSUE TITLE
Network down flag with splash screen

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#1074]
Scenario: network is down/not working properly but looks like it is up.
This to provide a manual way to force the app to show a message instead of the main app.

This is a manual intervention.

Use flag to render network down splash screen.

Effects all pages on token frontend

<img width="728" alt="Screenshot 2021-12-13 at 16 06 42" src="https://user-images.githubusercontent.com/13255539/145846682-371e5d06-e2e4-4891-80c8-79a0687fac84.png">
Shows loading spinner turns into an explanation.

**Comment by campbellssource** [comment]
To test
- In an environment, set the flag to show this message (will require netlify access). flag string:`REACT_APP_NETWORK_DOWN`. if tue this behaviour will be active (the app will show splash not normal app)

**Comment by cpuja84** [comment]
When the flag REACT_APP_NETWORK_DOWN is set to 1 on netlify and site is republished, accessing any of the below links on TFE on Staging throws the network down message correctly.

https://staging.token.vega.xyz
https://staging.token.vega.xyz/rewards
https://staging.token.vega.xyz/governance

![Screenshot 2021-12-17 at 16 46 34](https://user-images.githubusercontent.com/69709857/146578998-a7438b9a-620e-4847-b1a0-344fd06c1c46.png)
