### ISSUE TITLE
Bug: 0 in vesting contract but some associations present

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/token-frontend#1077]
We end up getting infinity as a value in the LockedProgress component which is an invalid property for setting the width of the progress bar.

After some digging it appears that for my vega public key (0x3d019f95a79e8aa82f2f9915bafac816100d40297cb432970772878f6e3ee92d) and my Ethereum key (0x72c22822A19D20DE7e426fB84aa047399Ddd8853) I have 0 in the vesting contract but some associations to the vesting contract, which results in a negative value for the notAssociated variable.

This appears as not a frontend bug but logging as something to investigate further.

<img width="608" alt="Screen Shot 2021-12-13 at 3 43 25 PM" src="https://user-images.githubusercontent.com/6803987/145906661-cf6888f7-8f7f-4b5e-b070-cfc65265d20f.png">

**Comment by C0deMunk33** [comment]
all the stake events I see are on the staking bridge, not the vesting contract, is there a chance you are pulling events from both contracts and that's why the code is confused?

**Comment by campbellssource** [comment]
@mattrussell36 My feeling is that this has been addressed. Can we close?
