### ISSUE TITLE
Messaging about historic rewards after checkpoint restart is incorrect

### ISSUE THREAD

**Issue by cdm** [vegaprotocol/token-frontend#1078]
After the mainnet1 restart the token website now lists "This Vega key has not received any rewards." and no history. The reason for this is that the historic rewards auditing is not kept from checkpoint to checkpoint.

We should perhaps change this phrase as I do have historic rewards and collateral available from them in my total balance (displayed bottom right) and will be confusing to community user

<img width="371" alt="Screenshot 2021-12-13 at 18 58 11" src="https://user-images.githubusercontent.com/149245/145970270-2d123724-7b6a-412b-b2da-29cb44a5a269.png">
s

**Comment by mattrussell36** [comment]
Suggestion for messaging from @campbellssource 

"The Vega key has not received any rewards since the previous network checkpoint. Any previous rewards will have been paid"

**Comment by candida-d** [comment]
We had a follow-up convo about this and agreed on: "The Vega key has not been credited any rewards since the previous network checkpoint."

**Comment by cpuja84** [comment]
This was tested on Stagnet2 - https://staging2.token.vega.xyz/rewards and signed off

![Screenshot 2022-01-11 at 10 41 15](https://user-images.githubusercontent.com/69709857/148928014-439a40e1-6a5c-42c9-83d5-fbb424941c51.png)
