### ISSUE TITLE
Prompt people to upgrade to new versions of the wallet when there is a new version out

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/token-frontend#1084]
FE can query the releases of vega wallet through the github API. If there is a new version we can show a message prompting users to upgrade to the new shinny version. As we are pre 1.0.0 and there can be breaking changes as per semver this would be a good shout.

https://api.github.com/repos/vegaprotocol/vegawallet/releases

and find the latest non-prerelease

**Comment by campbellssource** [comment]
Suggest adding a line to the top of the wallet when there is a new version 
<img width="556" alt="Screenshot 2021-12-17 at 17 39 38" src="https://user-images.githubusercontent.com/13255539/146585593-41734a50-cb35-4e18-82ce-294e0dd06051.png">
