### ISSUE TITLE
Add a warning to the withdrawals screen that tells users withdrawals will be lost if not compelete before checkpoint

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#1085]
<img width="748" alt="Screenshot 2021-12-16 at 08 25 43" src="https://user-images.githubusercontent.com/13255539/146335121-256a0d19-2e04-44e7-8a49-fd8dcdb17762.png">

Suggest adding a warning call out on the withdraw page.

and another one on the withdrawal**s** page that just talks about loosing a withdraw on reset.

**Comment by jeremyletang** [comment]
Can you explicitly add some alike: “whatever the amount of token you withdraw, and depending on the gas price, the gas will be > $100 and < $400”?

**Comment by candida-d** [comment]
Done in #1087 and updated in #1114

**Comment by jtsang586** [comment]
Warning verified on the Withdrawals page
