### ISSUE TITLE
Newly created open proposals not showing up on TFE / Governance tab on Stagnet1

### ISSUE THREAD

**Issue by cpuja84** [vegaprotocol/token-frontend#1091]
Newly created open proposals not showing up on TFE / Governance tab on Stagnet1 -

Proposal Query -
query {
 proposals {
    id
  reference
  state
  datetime
  errorDetails
  }
}

Response -
  {
        "id": "082f0b555b8ef759098e6c5b4adada93235a43e0a15c1fc616243d4f34b39f5f",
        "reference": "",
        "state": "Open",
        "datetime": "2021-12-16T16:32:57.783436094Z",
        "errorDetails": null
      },

![Screenshot 2021-12-16 at 16 39 56](https://user-images.githubusercontent.com/69709857/146412259-f72f2230-3d5f-4c80-ab59-8748dae65374.png)

Open Proposal on Console -
![Screenshot 2021-12-16 at 16 40 39](https://user-images.githubusercontent.com/69709857/146412372-9e70f8c1-0863-446f-8a97-9698eafef099.png)

**Comment by mattrussell36** [comment]
Everything looks as expected right now. There are 15 proposals on stagnet1 all of which are showing on both console and TFE.

**Comment by campbellssource** [comment]
Closing this as looks good for now, Governance will get some more attention in the near future.
