### ISSUE TITLE
Updated display of validators on staking page

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#1095]
On the staking page there is list of validators. This to update to a new design using components in the design system

<img width="400" alt="Screenshot 2021-12-17 at 14 28 24" src="https://user-images.githubusercontent.com/13255539/146559324-73c1b724-5b2e-41d1-b449-c756235409b7.png">

from the design system: Nominate list [design](https://www.figma.com/file/F995ESZ0QMpTBuQWGAgLRz/Vega-team-library?node-id=1121%3A76342), it has 4 states.
<img width="873" alt="Screenshot 2021-12-17 at 14 29 06" src="https://user-images.githubusercontent.com/13255539/146559414-db3b0267-9414-4e79-a201-014574f976ce.png">
- Overview
- this epoch detail
- next epoch detail
- previous epoch detail

**Note:** at time of writing the details of the penalties that have been applied in a previous epoch was not implemented. here is one example of a penalty https://github.com/vegaprotocol/vega/issues/4491. if none are implemented. 
if nothing is implemented either don't show the chevron, or show a line that links to the docs about staking penalties.

Note: the "Your nomination" is a separate ticket but could be done in the same feature branch PR

**Comment by gordsport** [comment]
Duplicate issue
