### ISSUE TITLE
Update the introduction on the Staking page

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#1096]
This in improve the introduction on the staking page.
<img width="782" alt="Screenshot 2021-12-17 at 14 45 11" src="https://user-images.githubusercontent.com/13255539/146561674-57dd8146-ea76-49c7-a7b0-155e219e6e65.png">

This could/should be done in the same Feature branch/PR as #1095

**Comment by candida-d** [comment]
Below is a suggested alternative, however... @campbellssource has included what'll be true in the future but not necessarily what's true now, so I'd like for us to chat about it/agree on a tactic before sending this copy live. 

My suggestion focuses on what's true right now, and I cut some detail with the hope that the docs link can provide more info - we can also use this as a way to ensure docs cover all the information needed about staking. 

> STAKING ON VEGA 
>   
> **Nominating validators**
> To nominate a validator, you will need to associate VEGA tokens in your Ethereum wallet to a Vega key. 
> 
> **Staking rewards**
> Rewards for securing the network are paid to validators and their nominators every 24 hours. Those rewards are funded by trading fees (when trading is enabled) or from the Vega treasury. 
> 
> Staking rewards are credited to your Vega key after each epoch ends. 
> 
> [Read more about staking on Vega](https://docs.vega.xyz/docs/concepts/vega-chain#staking-on-vega)

**Comment by candida-d** [comment]
@mattrussell36 @dexturr - going to talk to Michael about w/c 10 Jan, so if you could hold off on this one until then, I would appreciate it :)

**Comment by campbellssource** [comment]
@candida-d The next version of core will penalise "over staked" nodes. The ticket where this was implemented was about "validator score" (which is how the penalty is realised)

**Comment by candida-d** [comment]
@campbellssource I've added something back in alluding to penalties. (I don't love it but I think it's ok for now)

**Comment by campbellssource** [comment]
This ticket to just be about the copy. the table in the mock up should not be done as part of this work
