### ISSUE TITLE
Chart showing how many tokens unlock when

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#1100]
Show a chart on the Tranches page to show how overview of how many tokens unlock and when

**Comment by cpuja84** [comment]
This was tested and signed on Staging 2 - https://staging2.token.vega.xyz/tranches
Able to access the chart even without connected with a Eth or Vega Wallet.
The chart works well with resizing and different screen sizes

![Screenshot 2022-01-10 at 15 44 00](https://user-images.githubusercontent.com/69709857/148794705-46cb9dd1-7751-4df5-adac-b7aedf63e6dc.png)
