### ISSUE TITLE
Bug: rpc error: code = NotFound desc = NotFound error on https://staging.token.vega.xyz/staking

### ISSUE THREAD

**Issue by Ditmir-Vega** [vegaprotocol/token-frontend#1109]
This only seems to be happening when going to the staking section of tokenfrontend on staging 

1. Connect your eth key and wallet
2. Go to https://staging.token.vega.xyz/staking 

Observer error message on the page . The existence of this  error message causes the page to become quiet long and takes a long time to scroll back down 

This is the query response 
{
    "errors": [
        {
            "message": "rpc error: code = NotFound desc = NotFound error",
            "path": [
                "party",
                "delegations",
                2,
                "node"
            ]
        },
        {
            "message": "rpc error: code = NotFound desc = NotFound error",
            "path": [
                "party",
                "delegations",
                3,
                "node"
            ]
        },
        {
            "message": "rpc error: code = NotFound desc = NotFound error",
            "path": [
                "party",
                "delegations",
                4,
                "node"
            ]
        },
        {
            "message": "rpc error: code = NotFound desc = NotFound error",
            "path": [
                "party",
                "delegations",
                0,
                "node"
            ]
        },

<img width="1440" alt="Screenshot 2021-12-29 at 15 50 53" src="https://user-images.githubusercontent.com/87758526/147679940-cfca89d9-bca0-400b-ba43-054573755022.png">
<img width="1224" alt="Screenshot 2021-12-29 at 15 48 45" src="https://user-images.githubusercontent.com/87758526/147679956-119b5e80-82aa-419c-937e-a42e380af7dc.png">

expected :  
1. Not sure what the cause of this error is but should be resolved 
2. If the error persists in future we should have a single error message instead of the repetition of the same

**Comment by Ditmir-Vega** [comment]
@campbellssource  Some designs needed to display the error message

**Comment by cpuja84** [comment]
@mattrussell36 - According to me this ticket should have the "base from master" label, meaning it needs to be tested on Staging / Stagnet1. Please let me know if I have got it wrong.

**Comment by cpuja84** [comment]
This was tested on Stagnet1 - https://staging.token.vega.xyz/staking.
The error is being handled appropriately now.
This error occurs for wallets which has staked to the Validators in the past and now the validators public key has been changed. This was done intentionally in Staging to test checkpoint reload changes.

![Screenshot 2022-01-10 at 15 01 59](https://user-images.githubusercontent.com/69709857/148787664-d5b7d061-0062-4fb6-9b14-e4fb28a25b31.png)
