### ISSUE TITLE
Make hosted wallet work in all dev environments

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/token-frontend#1130]
Currently working in testnet but devnet, stag1 and stag2 is does not work

Needs a map of hosted wallet URL and environment so the correct environment is detected

**Comment by campbellssource** [comment]
I'm closing this for the same reason mentioned here: https://github.com/vegaprotocol/token-frontend/issues/1036#issuecomment-1025755464 i.e. we don't want to spend time supporting the hosted wallet
