### ISSUE TITLE
Set upe network parameter proposals with different states and dates to support execution of governance automated tests suite

### ISSUE THREAD

**Issue by cpuja84** [vegaprotocol/token-frontend#1141]
Investigate creation of test proposals with different states and dates to support execution of governance automated tests suite.
It's easier to create various proposal types manually which can then feed into test data for automation tests suites. It's confirmed that LNL checkpoints doesn't restore active open proposals and restores enacted proposals (most likely the values in the system somewhere and not the actual proposals on Console / TFE)

**Comment by campbellssource** [comment]
This to be considered as part the null blockchain work #1098 the creation of proposals could be automated.

**Comment by campbellssource** [comment]
Null blockchain doesn't yet have enough scripts in place to use yet. For now we'll need to create something manual

**Comment by gordsport** [comment]
Close as will use VegaCapsule
