### ISSUE TITLE
Make use of updated rewards API with pagination

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/token-frontend#1157]
Right night you end up with a massive list of rewards as a new entry is added for every epoch.

`Party.rewards` api is now updated to included pagination so we can build that in to the ui.

- [ ] Only show rewards from last 3 epochs by default
- [ ] Allow user to paginate back to previous epochs and review reward data.

**Comment by gordsport** [comment]
Rewards pagination in:
- https://github.com/vegaprotocol/data-node/issues/567
