### ISSUE TITLE
Validator Performance

### ISSUE THREAD

**Issue by ettec** [vegaprotocol/token-frontend#1159]
Add Validator Performance information to token frontend

Validator Performance and rawScore is now exposed on Node gql queries, e.g:

{
nodes {
    performance
    rawScore
  }
}

`rawScore` reflects the validator score before `performance` is applied.   The `score` attribute now reflects the validator score after the `performance` has been applied.  `performance` currently varies between 0 (bad) and 1 (good).

**Comment by campbellssource** [comment]
This will be done as part of https://github.com/vegaprotocol/token-frontend/issues/1273.
Closing this ticket as the API has changed since, and these details are included there.
