### ISSUE TITLE
Associate/dissociate form "Via Vesting contract" option is disabled where it shouldn't be

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#1164]
In this case I have tokens in the vesting contract and none in my wallet.
The associate form shows the Via vesting contract appears to be disabled. 
<img width="1108" alt="Screenshot 2022-01-28 at 16 35 26" src="https://user-images.githubusercontent.com/13255539/151586049-c1a8fd17-44b1-44ae-964b-7d05c3ac93c8.png">

Intended: if you have tokens in the vesting contract the option should not be disabled.

The dissociate form has the same issue: 
<img width="690" alt="Screenshot 2022-01-28 at 16 34 18" src="https://user-images.githubusercontent.com/13255539/151585948-834e90e7-43f6-4966-8ac3-42b7d6654de2.png">

It is still possible to stake as the option is selected but if you select wallet you then can't select vesting without refresh

**Comment by dexturr** [comment]
Not a bug, this is bad configuration on the FG environment :+1:
