### ISSUE TITLE
Use wallet endpoint for version checking

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/token-frontend#1172]
We have some logic for checking if there is a new version on TFE. The wallet has the same logic, but better with checks for pre release versions and if you are on an unstable version. There is a ticket https://github.com/vegaprotocol/vegawallet/issues/474 to offer an API so the logic can be shared and we can consume it.

We should replace the existing logic and allow this call to tell us the new version and release URL.

**Comment by campbellssource** [comment]
TODO: make sure types are correct and regenerate Vega wallet service client package.

**Comment by dexturr** [comment]
In light of https://github.com/vegaprotocol/vegawallet/issues/474#event-6099169827 this is no longer relevent
