### ISSUE TITLE
Create the simplest make a proposal form

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#1229]
<img width="1617" alt="Screenshot 2022-04-12 at 10 49 41" src="https://user-images.githubusercontent.com/13255539/162932789-95685038-5b2b-4a4d-bd30-ba1fa1de6eff.png">

- new form at /governance/propose
- text field input that expects full JSON proposal
- no client side validation yet
- submit button:
  - if proposal fails in wallet: refresh form with previous input, and error message.
  - if proposal is submitted but the status returned is `ProposalState.rejected` on chain, refresh the form with previous input and show error details: `proposal.errorDetails [String]`, `rejectionReason: ProposalRejectionReason`
  - if proposal is submitted and is any other status, the user is redirected to the proposal details page

**Comment by dexturr** [comment]
Cannot redirect to proposal after creation due to this issue:
https://github.com/vegaprotocol/data-node/issues/514

**Comment by dexturr** [comment]
Could poll, but that's yet more polling logic in this application that needs to be rewritten yet again
