### ISSUE TITLE
Fix connection to rest API

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/token-frontend#1230]
The assumption on connections to the rest api is they will be present on the same URL data node is served from.

This is not always the case, while true in Vegas own dev networks is not true for mainnet.

We need to fix this using an appropriate environment variable

**Comment by gordsport** [comment]
Hey @dexturr 
It looks like and env variable is being used, can you confirm this is still required?

**Comment by dexturr** [comment]
Nope
