### ISSUE TITLE
Bug: Staking broken on environments

### ISSUE THREAD

**Issue by Ditmir-Vega** [vegaprotocol/token-frontend#1235]
On https://dev.token.vega.xyz/ - Once the ethereal transaction starts , it times out and doesn’t get the confirmations needed .

On localhost:3000 (locally pointing to devnet) - returns an error delegating to a node 

On https://staging.token.vega.xyz/ - There is an RPC error on the page when the user navigates to staking page

<img width="942" alt="Screenshot 2022-03-25 at 08 19 25" src="https://user-images.githubusercontent.com/87758526/160095925-152c71ae-7e91-42b8-b864-0eeb41d9451d.png">
<img width="886" alt="Screenshot 2022-03-25 at 08 25 03" src="https://user-images.githubusercontent.com/87758526/160095935-e07f7048-57bc-4d51-b508-5f0c85b2a06b.png">
<img width="953" alt="Screenshot 2022-03-25 at 09 11 56" src="https://user-images.githubusercontent.com/87758526/160095938-437000c1-99cd-49f8-bb36-5bf1e70e7b7d.png">

![Uploading Screenshot 2022-03-25 at 09.12.24.png…]()

**Comment by dexturr** [comment]
Not a FE bug
