### ISSUE TITLE
Bug: PENDING TRANSACTIONS icon disappears if the user refreshes the page

### ISSUE THREAD

**Issue by Ditmir-Vega** [vegaprotocol/token-frontend#1237]
If the user refreshes the site while a pending transaction is happening , the icon on the top right of the page will no longer be present

to reproduce 
1. Go to token site 
2. Go to Staking > Association
3. Associate some tokens 
4. When the pending icon is displayed , refresh the page 

Expected : The pending transactions icon should still be visible if the user has pending transactions still in progress after refresh 

Actual : The pending transactions icon disappears and user cannot retrieve the status / block explorer of the pending transaction

**Comment by dexturr** [comment]
Not a bug, intended with current implementation. Please open a feature request if this is needed for something
