### ISSUE TITLE
CAPSULE-TFE - Create data sets for TFE tests

### ISSUE THREAD

**Issue by Ditmir-Vega** [vegaprotocol/token-frontend#1244]
TBD - 
some general config and set up needed for TFE 
 - existing proposals, 
- new ethereum ganache wallets for imporT
- REWARD POOL topped up
- Tranches - locked and unlocked tokens 
- Claim codes 
- DEX liuidity ? (Have an active liquidity campaign )

**Comment by gordsport** [comment]
Closing as a dupe of:
- https://github.com/vegaprotocol/token-frontend/issues/1254

points in this issue now captured in that issue
