### ISSUE TITLE
Withdrawal form: the unit on the amount filed should change based on the asset you have selected

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#1275]
At the moment the input form amount always has a "VEGA" unit badge on the right side. 
This should change to the symbol of the asset the you have selected.

here the asset is tbtc (top drop down) but the but the unit badge is still VEGA
<img width="670" alt="Screenshot 2022-04-12 at 17 16 43" src="https://user-images.githubusercontent.com/13255539/163008432-804ae5e8-0aeb-4931-83d9-dffef259ba5f.png">

**Comment by gordsport** [comment]
Closing: Withdrawal form now used from the monorepo which changes behaviour slightly
