### ISSUE TITLE
Associated tokens not available for staking 

### ISSUE THREAD

**Issue by Ditmir-Vega** [vegaprotocol/token-frontend#1280]
## Description

When the user is associating tokens , the balance is not being updated for their vegawallet. This in turn is resulting in a wrong balance being displayed and a wrong amount for staking available

## Environement

site : Testnet - Fairground 
https://token.fairground.wtf/

wallet:
used v0.13.2 and used latest 0.14.1 

## To Reproduce

1. Go to https://token.fairground.wtf/ 
2. Ensure that you have connected your vega wallet and your etherum key 
3. Go to association and associate some tokens 
4. wait for the association to happen and check your balance on the right side under the vegawallet section 
5. go to staking page
6. attempt to stake the amount you have just associated

## Screenshots
<img width="1163" alt="Screenshot 2022-04-21 at 08 45 04" src="https://user-images.githubusercontent.com/87758526/164417180-d06286b3-a522-47d4-ae44-0cc3d9a38a52.png">
<img width="1322" alt="Screenshot 2022-04-21 at 08 44 42" src="https://user-images.githubusercontent.com/87758526/164417186-a7499fa6-c301-48a6-91bf-14bb5f99caf5.png">

<img width="325" alt="Screenshot 2022-04-20 at 15 34 24" src="https://user-images.githubusercontent.com/87758526/164417266-0a3daa78-9189-4133-af2e-6f2ad0e27a87.png">

## Your browser information:
Chrome 

## ETH Wallet software:
Metamask

What ETH wallet software did you use? e.g. Metamask.
What's your address?

## Vega Wallet software version:

What version wallet software did you use? Run the following:
What's your pubkey?

vegawallet: 
Keys {
    "keys": [
        {
            "index": 1,
            "pub": "e6b309878f91afb547bb9bedc89d7e538f1e20f0b85d7a433b9fca1fb505285c",
            "algorithm": {
                "name": "vega/ed25519",
                "version": 1
            },
            "tainted": false,
            "meta": [
                {
                    "key": "name",
                    "value": "UI_TEST_1 key 1"
                }
            ]
        }
    ]
}

Key pair is: not tainted
Tainting a key pair marks it as unsafe to use and ensures it will not be used to sign transactions.
This mechanism is useful when the key pair has been compromised.

ETH WALLET : 
ADDRESS: 0x9804C6E98dA75e3271ccE3aA56728FD8e9376155

Etherscan links to show successsful association
TXN HASHES 
- https://ropsten.etherscan.io/tx/0xf78b5225ce14c55037afe2b6092d2bf6835ae1fe73e57abfc7ecb0a492f2f93d
- https://ropsten.etherscan.io/tx/0x6fa02df70947cdb2e613f17f9220433da90252004149e42af40dd28aaf89657e
- https://ropsten.etherscan.io/tx/0x4ebdc76f08433881be27db3ccbfc993abe85390a3aed3c4207ce8de271c0ebc9

**Comment by Ditmir-Vega** [comment]
CREATING A NEW WALLET DID NOT REPRODUCE THIS ISSUE , but the existing wallet still has the issue 
new wallet 
Wallet version:
2
First public key:
ae0d7dccb7f6e1fa613a7e2c537a72747ee8bde8c7666ad3a36d33a95887c74f

**Comment by gordsport** [comment]
@AndyWhiteVega @jtsang586 - please can one of you have a go to recreate this issue?

**Comment by gordsport** [comment]
CLose as not an issue
