### ISSUE TITLE
Confirm URL to use for GraphQL queries

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/token-frontend#297]
Token front end needs to speak to the Vega network to which it corresponds. For example, our https://staging.token.vega.xyz needs to point to stagnet, to fetch the list of current validators. The problem with this is that hard coding every network that we might want to communicate with is impossible: for some networks, we don’t know what node to query to fetch the lists of… nodes we can query. It’s easy in stagnet - we set the host names. 

# Long term solution
The Inventivised Data Node specification contains a rich API for discovering other nodes on the network. This will be the proper source of data node lists

# Short term solution
Right now, *go-wallet*, *token-frontend* and *console* all have to speak to Vega nodes. Currently, go-wallet relies on editing the config directly, and token-frontend relies on a hard coded list. However, go-wallet (as part of ticket x) is moving to fetch a list from Github. This list will be committed in the networks repo, and will also be enough for us to bootstrap the token front end. So lets use that. 

# Shorter term solution
See comments

**Comment by campbellssource** [comment]
another update: this also exists: https://graphql.vega.community

**Comment by campbellssource** [comment]
There is another option for Token Front End connecting to mainnet nodes, https://github.com/vegaprotocol/token-frontend-api-proxy. it doesn't currently rotate

So that leaves us with:
https://graphql.vega.community which does rotate
https://github.com/vegaprotocol/token-frontend-api-proxy as an option if ☝️ fails
followed by some other bridges we can cross if/when we get to them

**Comment by dexturr** [comment]
I began prepping a release for this, however I do not have the new ERC20 bridge address so this is currently blocked by that

**Comment by cpuja84** [comment]
Hi @campbellssource @dexturr - Does this needs to be QA'ed ? Doesn't look like but still wanted to confirm with you both.
