### ISSUE TITLE
Update Validator meta data with data from API

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#383]
https://github.com/vegaprotocol/networks/blob/master/testnet1/genesis.json

```  "A9dCI5URaK3MZnGg7OXq1ddjdqS241/9rLuHuPKWvN8=": {
        "vega_pub_key": "498fedb8e1637bde2493abff4f58d543a85e7c29e7e27ebce00ace8708894a5d",
        "ethereum_address": "0xa8CE9eF6ac6C4a1cE18aEd13bA1EFfa718c0e481",
        "info_url": "https://lovali.xyz",
        "country": "FI"
      }
```

https://www.figma.com/file/PPZp6wIZmhgTemLrIozO1A/token.vega.xyz?node-id=2578%3A9220

**Comment by pgriscti** [comment]
Hi @campbellssource, what does the "show details" show when expanded?

**Comment by campbellssource** [comment]
@pgriscti the hiding and showing details is for another task. All the data we have for a node should just be listed for now. A new layout may use a show hide thing with the intention of pulling the form up the page, but we could instead move the form to another page
