### ISSUE TITLE
ethereum address should use monospace fonts

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#389]
all instances of an ether address should display the address in a monospace font.

**Comment by cpuja84** [comment]
This is Done now !! 

![Screenshot 2021-11-30 at 16 41 24](https://user-images.githubusercontent.com/69709857/144089628-ddf861b3-591d-4a7f-9197-aef8aa828803.png)

![Screenshot 2021-11-30 at 16 41 33](https://user-images.githubusercontent.com/69709857/144089644-51777cf3-2c01-45ae-956b-e770d564020a.png)
