### ISSUE TITLE
Usability update: better feedback on successful/pending deposit flow.

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#411]
- [x] button back to check rewards. possibly a dupe here: https://github.com/vegaprotocol/token-frontend/issues/425 
- [x] show/hide pending stake based on state #410
- [ ] New design for the block that shows a market+reward
  - [ ] show / hide details
  - [ ] include link to the sushi analytics page in title
  - [x] always use the secondary button style
  - [x] some sort of epoch detail (could be text instead of bar)
  - [x] include units (VEGA or SLP) for each applicable row
  - [ ] APY and Incentive reward in one row
  - [ ] 5 different states, connect, you have 0 SLP, you have some SLP but it isn't staked, you have a pending stake, You have an active stake
  - [ ] @campbellssource can update copy on all labels

**Comment by dexturr** [comment]
Closing as SLP is finished and doesn't look like it's coming back
