### ISSUE TITLE
Create some real proposals for testing

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#460]
We've tested the governance functionality with mocks already. This ticket is to 
- Create some real proposals on a network, test that they appear appropriately (along with the vote status) 
- Test that users can vote, change vote and that the vote status is reflected

- [ ] We may need to use the API to make proposals as (at time of writing) it is not possible to make proposals via the Console until https://github.com/vegaprotocol/console/issues/6448 and https://github.com/vegaprotocol/console/issues/6449

**Comment by cpuja84** [comment]
Closing this story as able to create valid proposals on devnet and staging abiding spam protection rules.
