### ISSUE TITLE
cypress test for the happy path Governance

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#462]
- given a proposal, has vote tokens
- can vote
- can see my vote

- [x] provide mocks
- [ ] data test IDs
- [ ] Cypress tests

**Comment by gordsport** [comment]
@Ditmir-Vega 
Does governance have automated tests yet? If not we can refine/schedule this issue

**Comment by gordsport** [comment]
Ticket for governance test exist - can be broken down again later if QA wishes
