### ISSUE TITLE
Add gas price to the website

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/token-frontend#562]
So @candida-d  and I were considering adding the gas price to the token front end.

It's a fairly small piece of work from our side, just where do we put it 🤔 

Related: https://ethereum.stackexchange.com/questions/60863/estimate-gas-price-not-gas-using-web3

![Screenshot 2021-10-06 at 11 59 20](https://user-images.githubusercontent.com/26136207/136190417-25bc21f8-eb7a-472e-8e81-e79d488ba62f.png)
![Screenshot 2021-10-06 at 11 58 51](https://user-images.githubusercontent.com/26136207/136190428-fe6d272b-d8b6-42c0-91df-2671c548c851.png)

**Comment by campbellssource** [comment]
Withdrawals are one of the more expensive transactions.
> looking at the ERC20bridge... the withdrawals are using approximately 450k to 500k units of gas, so one could estimate the cost of a withdrawal by doing `500000 x gas_price x eth_usd`
