### ISSUE TITLE
Handle invalid number inputs on "amount of token"

### ISSUE THREAD

**Issue by Ditmir-Vega** [vegaprotocol/token-frontend#589]
The user can enter a number with unlimited numbers after the decimal point . We should restrict the entry to a max length. It looks like it is cutting the number off after certain decimal points in the key/wallet 

1. go to stake > associate tokens 
2. In the association box enter a crazy long decimal number 

Result: The user is unrestricted in maximum they can put

Also see all off the linked tickets below for other cases where number inputs could be validated

**Comment by campbellssource** [comment]
Here is the design for input/price
<img width="939" alt="Screenshot 2021-12-17 at 14 18 15" src="https://user-images.githubusercontent.com/13255539/146557874-e8c32389-2047-460c-b9aa-63b2771fb9f1.png">
https://www.figma.com/file/F995ESZ0QMpTBuQWGAgLRz/Vega-team-library?node-id=1140%3A65268

Where a form contains an invalid input, the submit button appears greyed out and an explanation of why the form is invalid re-appears on attempt to submit (buttons are never disabled just appear to be so, they should have an action on click that helps the user find the problem)
<img width="391" alt="Screenshot 2021-12-17 at 14 21 39" src="https://user-images.githubusercontent.com/13255539/146558312-b6728ed5-3436-4157-a579-b6d4432a8826.png">
