### ISSUE TITLE
List all rewards for connected Party (by epoch news first)

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#619]
https://www.figma.com/file/PPZp6wIZmhgTemLrIozO1A/token.vega.xyz?node-id=3812%3A66704

- [x] new page at `/Rewards` ☝️ 
- [x] Includes wallet sidebar (both wallets) https://github.com/vegaprotocol/token-frontend/issues/352
- [x] Intro to Rewards (copy only) https://www.figma.com/file/PPZp6wIZmhgTemLrIozO1A/token.vega.xyz?node-id=3811%3A61678
- [ ] summary of active rewards (copy only) as above (ignore the Data node section for now)
- [x] Epoch count down https://www.figma.com/file/F995ESZ0QMpTBuQWGAgLRz/Vega-team-library?node-id=525%3A15887
- [x] Section: Rewards for Vega key
  - [x] Show each key/value for given reward type
- [x] Add "Rewards" to top nav (Governance last, rewards 1 before)
- [x] For each epoch, each rewards that the user has for that epoch (right now all rewards are hardcoded to a single type, assume this will come later and be called "Staking"
- [ ] ~~Pagination as required. DESIGN TODO~~

**Comment by mattrussell36** [comment]
I'm nearly there with this. A few things to note:

- Summary of active rewards - Don't think this value exists in the API anywhere and I'm not sure it makes sense to query for all parties and all rewards under those parties. 
- Vega wallet not connected state - Lets do this in a follow up ticket as wallet side bar not implemented yet.
- Pagination of rewards. We'll need a core ticket for this.

**Comment by mattrussell36** [comment]
pagination follow up: https://github.com/vegaprotocol/token-frontend/issues/780
vega key dropdown follow up: https://github.com/vegaprotocol/token-frontend/issues/781

**Comment by cpuja84** [comment]
Rewards UI are working fine, Hence marking this ticket as Done
