### ISSUE TITLE
Test: Associate from Tranche 0

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#627]
We have a bunch of Investors and Vega team members who held the V1 token. These were used to create V2 tokens which are held by the vesting contract.

As far as I know these V2 tokens have not been issued into a tranche and are therefore in tranche 0.

In theory someone with tokens in tranche 0 can go to `/Vesting` and see the tokens they have in tranche 0 (which does not appear on the `/tranches` page).

They could associate these tokens via the vesting contract.

This ticket to test this scenario, as well as some branches from it.
- Dissociate
- after association from tranche 0, tokens get moved to a tranche. Test this. as well as dissociation, and redeeming.

**Comment by gordsport** [comment]
@JonRay15 
Is this issue still valid as Tranche 0 has been done see: https://vegaprotocol.slack.com/archives/C8W4JQ27P/p1636059788227000


(cc @campbellssource @Ditmir-Vega)

**Comment by JonRay15** [comment]
Yes this is resolved.  Per the discussion with Danny on Slack yesterday I think we have already done everything we can do to identify and transfer all the old V1 balances.  To the best of our knowledge there are none left to worry about.
