### ISSUE TITLE
Withdraw collateral

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#629]
This to allow users to withdraw assets held on their Vega key.

- [x] link from wallet sidebar with withdraw page #628 
- [x] Drop down for selecting asset to withdraw (logic to default to an asset with a non-zero balance) or deep link to a specific asset
- [x] input for amount (use max link for all that is in general account)
- [x] input for eth wallet to withdraw too (can use connected wallet)
- [x] Button to trigger action in connected eth wallet
- [x] track transaction progress
- [x] handle errors

https://www.figma.com/file/PPZp6wIZmhgTemLrIozO1A/token.vega.xyz?node-id=3977%3A101066

**Comment by campbellssource** [comment]
@mattrussell36 I think we can mark this as done?

**Comment by mattrussell36** [comment]
Yup. Closing!
