### ISSUE TITLE
Update button naming to ' Associate tokens' and 'Disassociate tokens'

### ISSUE THREAD

**Issue by Ditmir-Vega** [vegaprotocol/token-frontend#652]
Currently there is a reference to 'wallet' both in the heading of step 2 [ STEP 2. ASSOCIATE TOKENS WITH A VEGA WALLET] and also within the buttons of STEP 2.

They both reference 'wallet' , As you can associate/disassociate tokens from vesting contracts too this might be misleading as you can go to next screen and choose either 'wallet' or ' vesting contract' to perform these actions

**Comment by campbellssource** [comment]
this to be done differently on https://github.com/vegaprotocol/token-frontend/issues/1096
