### ISSUE TITLE
Tranches Query is very slow

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/token-frontend#655]
# Bug report

## Describe the bug
TrustWallet with WalletConnect  isn't working on android. Further details here:
https://vegaprotocol.slack.com/archives/C8WS7M50E/p1634304193383300

## Environement

Ethereum mainnet 

## To Reproduce

1. Go to the token website on an android device.
2. Try to connect with TrustWallet/WalletConnect

## Expected behavior

You can retrieve your Ethereum address

## Your browser information:
Android browsers

## ETH Wallet software:
TrustWallet

**Comment by emilbayes** [comment]
Did you triage this one?

**Comment by campbellssource** [comment]
@emilbayes this still needs to be done, will discuss in planning. unless you want to offer a potential solution to the issue?

**Comment by campbellssource** [comment]
from another ticket -
Stop over fetching and re-fetching tranche data unnecessarily
- Figure out a better way to get tranche data, hopefully not fetching all events
- Optimise chain queries for tranches page and tranche/1 page.

Error: Internal JSON-RPC error.

Sentry Issue: [TOKENVEGAXYZ-6E](https://sentry.io/organizations/vega-o3/issues/2622155894/?referrer=github_integration)

```
Error: Internal JSON-RPC error.
{
  "code": -32005,
  "message": "eth_getLogs block range too large, range: 21134965, max: 100000"
}
  at _fireError (../node_modules/web3-utils/lib/index.js:50:17)
  at apply (../node_modules/web3-core-method/lib/index.js:540:30)
  at cb (../node_modules/util/util.js:689:22)
  at callbackifyOnRejected (../node_modules/util/util.js:666:10)
  at run (../node_modules/process/browser.js:153:14)
...
(1 additional frame(s) were not displayed)
```
