### ISSUE TITLE
Numbers in table for staking validators overun into 2-3 fields

### ISSUE THREAD

**Issue by Ditmir-Vega** [vegaprotocol/token-frontend#669]
We should look at doing some tidy up here as some numbers are too long .

1. Truncate values to 1 line 
2. Display numbers to 2dp
3. Update the layout of the table to accomodate large numbers
4. Highlight clearly what is the users stake and what is the node stake

**Comment by campbellssource** [comment]
there was a quick fox for this implemented and a new design incoming
