### ISSUE TITLE
Copy to clipboard being applied to etherscan link inappropriately

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#673]
This link to etherscan link gets a copy to clipboard on hover, it shouldn't. 

Or maybe it should be the thing that should end up on your clipboard is the transaction rather than the text "Copy to clipboard"

This from the pending transaction state when associating tokens on /staking/associate
<img width="413" alt="Screenshot 2021-10-20 at 11 37 12" src="https://user-images.githubusercontent.com/13255539/138078367-7efac9dc-b96c-4573-ae5d-25970a39e7ff.png">

**Comment by cpuja84** [comment]
This is working in Staging. Marking the story as done.

**Comment by mattrussell36** [comment]
This still shows

**Comment by campbellssource** [comment]
Test: find a number of uses of this and check it is displaying correctly.
- if shows address, show pop over with copy to keyboard link
- if link, there is no copy function... just links to etherscan

**Comment by cpuja84** [comment]
This is tested and signed off on Stagnet2 https://staging2.token.vega.xyz/staking/associate

For address when mouse is hovered over, copy to clipboard hover text is displayed which copies the link on clipboard and pasting that opens up a copied link 
![Screenshot 2021-12-17 at 13 21 30](https://user-images.githubusercontent.com/69709857/146550968-e8c51fd9-47ef-47fc-90f7-f90ceb836252.png)

For link, copy to clipboard text is no longer there, and the user can only click on the link
![Screenshot 2021-12-17 at 13 22 01](https://user-images.githubusercontent.com/69709857/146551095-a4de5374-7de2-4384-a331-cafa868dd91e.png)
