### ISSUE TITLE
A feature to allow user to switch from “use connected Vega wallet” to a text input to “Disociate from” aribtuary string

### ISSUE THREAD

**Issue by cpuja84** [vegaprotocol/token-frontend#691]
As a user who has run the stake (aka associate) function to a random string (or anything that isn't a Vega key they can now connect to) I wish to be able to unstake, so that I can actually stake to my Vega key, or send my VEGA tokens to another eth address

The feature would allow you to switch from “use connected Vega wallet” to a text input to “Disociate from” aribtuary string.

**Comment by dexturr** [comment]
Is this the same as #1015?

**Comment by campbellssource** [comment]
Yes it is, closing as duplicate
