### ISSUE TITLE
TOKEN - UI showing keys with 0 association

### ISSUE THREAD

**Issue by Ditmir-Vega** [vegaprotocol/token-frontend#694]
I did some test for associating  Many Vega wallets to 1 ETH Key . 

After i had dis-associated all of the vega keys i noticed for the eth key field it still showed that my eth key had some associations to vega keys , with a balance of 0

It should not display the keys if nothing is associated . However could this be that because you have already approved it >?

**Comment by mattrussell36** [comment]
Reopening as hasnt been QA'd yet
