### ISSUE TITLE
Change name of field for tokens associated with Vega key

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/token-frontend#702]
There's been some confusion about what the field "$VEGA associated with a Vega key" means 
![image](https://user-images.githubusercontent.com/62548908/139278084-35207e6b-a38a-4094-9f5a-3c6355a2ee25.png)

ref: https://vegaprotocol.slack.com/archives/C8WS7M50E/p1635430058209500

Suggestions from @davidsiska-vega:
- a. associated with Vega chain
- b. associated with Vega network

@campbellssource What do you think, any preference? I weakly vote for b.

**Comment by MM0819** [comment]
I vote for removing the associated VEGA, it's not useful information IMO. Then simply rename the "STAKED ON VEGA VALIDATOR" to "Total Stake" or "Total Staked VEGA".

**Comment by candida-d** [comment]
> I vote for removing the associated VEGA, it's not useful information IMO. Then simply rename the "STAKED ON VEGA VALIDATOR" to "Total Stake" or "Total Staked VEGA".

Thanks @MM0819!

**Comment by dexturr** [comment]
This has been done

**Comment by cpuja84** [comment]
This work has been done 

![Screenshot 2021-11-26 at 15 08 32](https://user-images.githubusercontent.com/69709857/143600560-5c7d0cca-3245-47b1-9784-1229d4084eb1.png)
