### ISSUE TITLE
Deposits to VEGA appear in associated too section of ETH wallet (they should not)

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#703]
To recreate.

Use a ETH key to populate the reward pool https://www.notion.so/vegaprotocol/Contracts-Cheatsheet-2fb290daaa4d4b71993c3ef49dfa57ff
(probably the same if you do a deposit.
e.g. of depositing to the reward pool on Stagnet1 https://ropsten.etherscan.io/tx/0x3daafcb30e69952e13e274b511525cc74914b9de3bf606ad853225b332592eda

Go to token front end. notice the association to `0x0000`
<img width="1126" alt="Screenshot 2021-10-29 at 15 32 56" src="https://user-images.githubusercontent.com/13255539/139453811-65200203-9561-4222-b798-d092ff69ed18.png">

Reward pool deposits and general deposits should not show up in this list. only Association actions.

**Comment by cpuja84** [comment]
This has been fixed
