### ISSUE TITLE
Prevent app loader fetching token info before decimals are set

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/token-frontend#706]
ContractsProvider mounts before the token decimals value has been fetched resulting in no decimals being applied on first render. This flashes up until the request for token.decimals completes. In some cases it appears to persist in this state.

https://vegaprotocol.slack.com/archives/C8WS7M50E/p1635430276210800

**Comment by cpuja84** [comment]
This issue didn't appear for me on Staging. The issue seemed to be random without any perfect way to reproduce but I'm satisfied for now that the issue has been resolved. Hence marking the ticket as closed.
