### ISSUE TITLE
Token FE lets a user try to withdraw nominated stake less than the minimum VEGA fraction of DP

### ISSUE THREAD

**Issue by cdm** [vegaprotocol/token-frontend#707]
During testing on Stagnet 1 yesterday I realised I could successfully withdraw nominated stake but at a value less than the minimum DP, see screenshot below:

<img width="786" alt="Screenshot 2021-10-31 at 13 47 01" src="https://user-images.githubusercontent.com/149245/139642378-15a719be-4f40-46a9-a9de-bf6aaf042f7e.png">

The outcome was successful, however in the next epoch ALL my stake nominated to that validator was removed.

**Comment by campbellssource** [comment]
duplicate #589

**Comment by campbellssource** [comment]
duplicate #589
