### ISSUE TITLE
Token FE wouldn't let me allocate my second set of fauceted VEGA tokens

### ISSUE THREAD

**Issue by cdm** [vegaprotocol/token-frontend#708]
I used the new rate limited faucet via console to deposit 5.00 VEGA for testing on stagnet. On first deposit all worked as expected.

I waited 24 hours, fauceted 5.00 more VEGA tokens to my Vega wallet, however the token FE would not allow me to deposit them and said I had none in my wallet.

<img width="1052" alt="Screenshot 2021-10-31 at 09 42 20" src="https://user-images.githubusercontent.com/149245/139646086-ee88dbcc-ee62-4d1a-8536-f11c9476b883.png">

I tried refreshing and reloading but it still said the same.

I managed to get the Token FE to recognise the tokens by depositing them into my VEGA general account using console, then withdrawing them back out to my etc wallet, again via console. At that point the Token FE immediately recognised they were in my wallet.

**Comment by campbellssource** [comment]
Small chance that this was due to one of the association between resets.
https://ropsten.etherscan.io/token/0xdc335304979d378255015c33abff09b60c31ebab?a=0x8ff5c070e1f9bc771fc65132086e6e220bcfd989

**Comment by mattrussell36** [comment]
This all seems to work okay for me (albeit I haven't waited 24 hours between attempts) but you have got yourself in an interesting state there where you have 5 in wallet (not associated) but can't associate them

**Comment by campbellssource** [comment]
I'm now also in this state.
