### ISSUE TITLE
Bug: Ethereum RPC instead of Infura

### ISSUE THREAD

**Issue by legg** [vegaprotocol/token-frontend#711]
# Bug report

## Describe the bug

Is possible to replace the REACT_APP_INFURA_ID in the token frontend with our own ethereum rpc? There is something in the code about web3 providers, but couldn't figure it out.

## Environement

Self hosted 

## Expected behavior

Make this optional
REACT_APP_INFURA_ID 

Add new build arg for ethereum rpc
REACT_APP_ETHEREUM_RPC

**Comment by mattrussell36** [comment]
Thanks for creating the issue. Looking into this.

**Comment by Mukz95** [comment]
Is this issue still up for grabs, would like to take this as a first issue

**Comment by gordsport** [comment]
Already implemented
