### ISSUE TITLE
Simultaneous nomination isn't working on Staging

### ISSUE THREAD

**Issue by cpuja84** [vegaprotocol/token-frontend#714]
It seems to be that when the multiple nominations simultaneously doesn't go through for multiple nomination simultaneously in the same epoch.

Basically assign tokens to all the nodes at the same time in different windows.

For me only the first nomination goes through and the rest get stuck / pending forever. The UI is stuck on Adding Vega Tokens to Node Screen ( only the first one goes through and remaining ones gets stuck), even after completion of epoch as below. It only goes away only if page is refreshed, then its goes to normal state without any nominations of course.
But if I don't refresh the page, it carries on for epochs and epochs. I'd have expected it refresh after the epoch at least as the nominations if doesn't got through are null and void for future epochs

![Screenshot 2021-10-28 at 13 05 49](https://user-images.githubusercontent.com/69709857/139708019-d8cae305-2a62-4599-9452-018f38ff816c.png)

![Screenshot 2021-10-28 at 13 02 11](https://user-images.githubusercontent.com/69709857/139707948-5d901f40-498b-4435-9587-e2eb6c679b88.png)

**Comment by mattrussell36** [comment]
So I've spent some time looking into this and found an additional (sort of related problem)

- If you delegate a second time to the same node, the loading state is inaccurate because it will immediately find the previous delegation. We might have to change the logic to see if the amount is greater or lower than the previous epoch if you added or removed stake.

**Comment by cpuja84** [comment]
I spent whole afternoon trying to replicate this and can confirm this is reproducible everytime if the validator nodes has got no earlier delegations / staking from the user. After the epoch passes through, the delegation if valid and applicable goes through respective validator nodes and the in progress message from the last epoch gets converted to successful message in the next epoch ( which is the current epoch now !). This success message is no longer relevant ( and misleading too!) as the staking has already gone through in the last epoch.

**Comment by cpuja84** [comment]
Simultaneous delegation is working in Staging for first time and later nominations. Hence marking this ticket as done.
