### ISSUE TITLE
Bug: Connectivity issue with MetaMask 

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/token-frontend#727]
# Bug report

## Describe the bug

When trying to associate staging VEGA on the staging token FE, I try to connect via MM and token FE gives me a "something went wrong" error. Once I moved some tokens, it allowed me to associate. 

MetaMask had no errors or activity, and it failed very quickly. (see video below) 

I tried this several times over the course of the day including after closing the tab and reopening, and also stopping and restarting the Vega Wallet too, just in case. 

Eventually I moved 3 tokens from one MM account to another.

Then, I was able to associate the remaining 2 tokens left in the original account. 

## Environment

What environment did this occur on?
Staging Version: 3f80aac6e2dc98ba975f674588e36d6188e243b0

## To Reproduce

1. Go to associate tokens 
2. Click on associate tokens to Vega wallet 
3. See error

## Expected behavior

The ability to associate. 

## Screen recording (2)
Original something went wrong: 
https://user-images.githubusercontent.com/62548908/140171240-de178348-2d6e-4bf5-9322-23895556a06b.mov

## Your browser information:

https://www.whatsmybrowser.org/b/BOEIT

## ETH Wallet software:

What ETH wallet software did you use? 
Metamask

What's your address?
0xF4da0Debd80A8c42b34C872e466EB77cE1e95A22 

## Vega Wallet software version:
0.9.2

**Comment by campbellssource** [comment]
This appears to be happening to people in the community too. 
https://discord.com/channels/720571334798737489/720571334798737491/905805837895892992
https://discord.com/channels/720571334798737489/720571334798737491/905802881389723649

**Comment by candida-d** [comment]
@dexturr Was able to replicate and got the following error message: 

` xError: sending a transaction requires a signer (operation="sendTransaction", code=UNSUPPORTED_OPERATION, version=contracts/5.5.0)
    at e.value (index.ts:225)
    at e.value (index.ts:237)
    at index.ts:412
    at l (runtime.js:63)
    at Generator._invoke (runtime.js:294)
    at Generator.next (runtime.js:119)
    at 10.e8aeadd7.chunk.js:2
    at new Promise (<anonymous>)
    at wn (10.e8aeadd7.chunk.js:2)
    at n.<anonymous> (10.e8aeadd7.chunk.js:2)
    at e.<anonymous> (vega-token.ts:35)
    at l (runtime.js:63)
    at Generator._invoke (runtime.js:294)
    at Generator.next (runtime.js:119)
    at r (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25) `
