### ISSUE TITLE
Bug: "Use maximum" allows staking of 5 VEGA when <5 is available

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/token-frontend#732]
# Bug report
Reported by multiple staking incentive participants

https://vega-testnet.nolt.io/267
https://vega-testnet.nolt.io/268
https://vega-testnet.nolt.io/272
https://vega-testnet.nolt.io/282
https://vega-testnet.nolt.io/286

## Describe the bug

When you use 4 (or N amount less than 100%) Vega to nominate 4 validators and select max amount for the next validator, there will still be 5 Vega (full amount) available to stake instead of 1 (remainder). 

## Environment

What environment did this occur on?

Fairground

## Expected behavior

Only the remaining amount is available to stake, not the full original amount of VEGA. 

## Screenshots

![image](https://user-images.githubusercontent.com/62548908/140305850-718b241f-b061-4593-8cc7-3048d25d00b7.png)

## ETH Wallet software:
What ETH wallet software did you use?

What's your address?
Hoping to get this info from 1 or both users - not available as of writing. 

## Vega Wallet software version:
What's your pubkey?
Hoping to get this info from 1 or both users - not available as of writing.

**Comment by pgriscti** [comment]
I cannot reproduce this, however, I did notice this issue: https://github.com/vegaprotocol/token-frontend/issues/737

**Comment by candida-d** [comment]
Follow up from the user who reported 272 on Nolt (possibly a separate issue though):

VEGA key: f998abed48c5e507206a2de6a213f1748c4a3e018aa7528501c208911423fc7c

yes, 0,5 should not be staked but somehow did get allocated to other validators. It was not me so I am wondering how they have been staked. You should see in your logs. Let me know if you need something else.

https://vega-testnet.nolt.io/272?comment=55bacb89-5bd2-46ac-999c-d8e1fe8b230d
