### ISSUE TITLE
It seems the front-end won't let me un-stake from a validator and re-stake during the same epoch.

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/token-frontend#734]
It seems the front-end won't let me un-stake from a validator and re-stake during the same epoch.

![image](https://user-images.githubusercontent.com/62546419/140321495-f06cfd2a-c4e3-456d-bc95-a4cd88cd72d3.png)

Also, the error message is misleading; I do have 5 VEGA associated it's just that they're all delegated in this current epoch.

**Comment by davidsiska-vega** [comment]
Bit more on my status: 
![image](https://user-images.githubusercontent.com/62546419/140321708-3fda0783-a858-405f-9f1c-6f1bddd57257.png)

**Comment by davidsiska-vega** [comment]
And my Vega key `60b7663c688cc720373d2bc7c3e01d93c416a25cb74fd11189a2767c11aaf20e`.

**Comment by ze97286** [comment]
it's actually not a UI bug, as I figured yesterday - it would happen when you already have all of your association nominated and you're trying to move stake between validators. It's fixed by https://github.com/vegaprotocol/vega/pull/4372

**Comment by cpuja84** [comment]
Retested this bug and it works fine. When I have 0 unstaked tokens and I try to delegate and undelegate multiple times to the same validator and other validators in the same epoch, the staked tokens are accurately updated. Hence marking this ticket as done
