### ISSUE TITLE
Newly staked tokens not shown in the wallet

### ISSUE THREAD

**Issue by pgriscti** [vegaprotocol/token-frontend#737]
The wallet does not always sync up with the amount staked after it's assigned.
Steps:
- selected a validator
- select an amount to be staked
- wait for the next epoch to start for the tokens to be staked
When the next epoch starts, the tokens are assigned to the validator, however this is not _always_ reflected in the wallet unless the user refreshes the browser

**Comment by candida-d** [comment]
This seems to be similar but the opposite, showing in the wallet sidebar but not in the main section - but linking just in case https://github.com/vegaprotocol/token-frontend/issues/759

**Comment by cpuja84** [comment]
This works fine now. So marking the story as done.
