### ISSUE TITLE
Add a Modal to introduce known issues on Token front end / aka release notes.

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#741]
There are some issues with the staking process that will not have a quick fix. For these we agreed that 

- Headline things we want people to know about. Particularly in cases where values don't show what people expect (due to waiting epoch/blocks)
- Link to know issues (docs/blog post) 
- Summary of release notes

**Comment by mattrussell36** [comment]
Should this modal open immediately when you load the site? Once the user closes it we could not show it again?

**Comment by mattrussell36** [comment]
Blocked until we have a link for the known issues doc/page

**Comment by cpuja84** [comment]
@campbellssource - I'm marking this ticket as done,let me know if that's an issue. Thanks !
