### ISSUE TITLE
Bug: Text field lets you input numbers of any size

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/token-frontend#742]
When a user inputs an extremely long number, the text field accepts it. Should the field stop people after a certain number of digits, or would that be too limiting? 

![image](https://user-images.githubusercontent.com/62548908/140501557-1176dfc3-da16-4e14-b785-ff4ba2fad04c.png)

Raised by user during fairground incentive: https://vega-testnet.nolt.io/284

**Comment by campbellssource** [comment]
duplicate #589

**Comment by campbellssource** [comment]
duplicate #589
