### ISSUE TITLE
RE-ENABLE automated cypress tests - Diagnose issues

### ISSUE THREAD

**Issue by Ditmir-Vega** [vegaprotocol/token-frontend#746]

**Comment by dexturr** [comment]
@Ditmir-Vega has this been done now or is there a new ticket for tracking this you and @edd are working on? Can we close this?

**Comment by edd** [comment]
@dexturr I thought we have done this now. I've silently dropped working on adding more mocks (sorry @Ditmir-Vega), but I think we are in a place where these should be running.

**Comment by cpuja84** [comment]
Confirmed with @Ditmir-Vega, this can be closed, marking this ticket to Done.
