### ISSUE TITLE
Randomise the order of validators

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#753]
The intention is to not bias the selection of validators.
Future iterations may contain sorts, or warning that help users select "Good" validators but not for now (and possibly even then, the default order should be random). 

The randomisation could happen on each load, but something that randomised on first load and then kept the order in that browser would be less janky for user.

more colour on this here, but I think this covers it: https://vegaprotocol.slack.com/archives/C01P24880JY/p1636385051158200

**Comment by dexturr** [comment]
The behaviour of this is such that the order should remain the same if until the browser is refreshed. Every time the browser is refreshed the list should change order. There is no guarantee that the order will be randomized in any specific way i.e. the same validator could be at the top/bottom after refresh with the ones in the middle in a different order.

**Comment by cpuja84** [comment]
This has been tested and signed off in Staging. Everytime the page is refreshed the order of the list of validators is random. Hence marking this ticket as done.

<img width="821" alt="Screenshot 2021-11-15 at 13 06 00" src="https://user-images.githubusercontent.com/69709857/141854204-e52ffd22-b6f7-4678-9d98-e1d16ba40ea7.png">
<img width="808" alt="Screenshot 2021-11-15 at 13 06 17" src="https://user-images.githubusercontent.com/69709857/141854207-ab554797-180e-44cc-bac3-b753c9cdff81.png">
<img width="855" alt="Screenshot 2021-11-15 at 13 06 42" src="https://user-images.githubusercontent.com/69709857/141854209-b6f45c7f-f692-4ea1-873f-d2255cb65e3f.png">
<img width="691" alt="Screenshot 2021-11-15 at 13 07 17" src="https://user-images.githubusercontent.com/69709857/141854212-73317621-086b-4930-b1fc-30611525d4bf.png">
