### ISSUE TITLE
Countdown not working on association page (TFE)

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/token-frontend#767]
When a user did an association it would start with: "Waiting for 5 more blocks" and immediately go to  "Crediting Vega key" after a single assocaition.

It should countdown showing `networkParameters.ethereumConfig.confirmations - currentNumberOfTxConfimrations` and only show the crediting vega key message when `currentNumberOfTxConfimrations => networkParameters.ethereumConfig.confirmations`

**Comment by pgriscti** [comment]
Hey @dexturr, I've fixed this last week. Is there an issue with the fix, or is the issue that it hasn't been deployed yet?

**Comment by dexturr** [comment]
Nope, must be a duplicate issue

**Comment by dexturr** [comment]
Oh hang on this is to track the qa I lied, just testing the fix you did

**Comment by cpuja84** [comment]
The countdown appears to be updating dynamically when trying to associate tokens for the user. Hence closing this story.

<img width="685" alt="Screenshot 2021-11-15 at 14 44 48" src="https://user-images.githubusercontent.com/69709857/141864848-1cb6cbe1-a60c-4d5e-bbf2-ff1c3496b143.png">
<img width="677" alt="Screenshot 2021-11-15 at 14 45 02" src="https://user-images.githubusercontent.com/69709857/141864852-ee1e9cdd-c74c-46b6-86f0-dcc9513fd142.png">
<img width="717" alt="Screenshot 2021-11-15 at 14 45 20" src="https://user-images.githubusercontent.com/69709857/141864857-71666da8-bedb-43aa-b0f2-a5225bb8c50b.png">
<img width="1152" alt="Screenshot 2021-11-15 at 14 45 51" src="https://user-images.githubusercontent.com/69709857/141864858-89693e8f-afab-40a2-8b9a-ecf47a29e394.png">
