### ISSUE TITLE
First nomination transactions shows as in progress until epoch is complete (TFE)

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/token-frontend#768]
First nomination transaction on any validator would show loading infinitely until the first epoch ended, even if the nomination was present in GQL.

This should now show the success state when the nomination is credited by core during the epoch and not only at the end of the epoch

**Comment by cpuja84** [comment]
Able to see the success message on TFE for first nomination to the validator. Marking this ticket as done.
