### ISSUE TITLE
Feature request: show date time the epoch ends

### ISSUE THREAD

**Issue by cdm** [vegaprotocol/token-frontend#769]
This might be personal preference, but I'd love to see when the **epoch ends** not when it started so I know when to check back and see my stake or get my rewards:

<img width="320" alt="Screenshot 2021-11-09 at 09 49 25" src="https://user-images.githubusercontent.com/149245/140901888-acb0c651-e18b-4bd3-b9b0-aa75c9f3d60a.png">

We could either:

* Show both
* Tap to swap between started/ends 
* Tell me I'm wrong and that people should only see started and count down lol

**Comment by cpuja84** [comment]
The epoch timer looks good
![Uploading Screenshot 2021-11-16 at 16.46.31.png…]()
