### ISSUE TITLE
Unable to distinguish rejected proposals on TFE- Shows You did not Vote

### ISSUE THREAD

**Issue by cpuja84** [vegaprotocol/token-frontend#789]
Unable to distinguish rejected proposals on TFE- Shows You did not Vote
When the proposal is rejected, the Token Front End doesn't tell you anything about it and shows _You did not Vote_

![Screenshot 2021-11-10 at 15 02 52](https://user-images.githubusercontent.com/69709857/141148319-bfee5b0a-6172-4457-a72f-8efb7d9c417b.png)

**Comment by cpuja84** [comment]
@campbellssource - To update with designs to include the whole lifecycle of rejections, approved votes etc

**Comment by campbellssource** [comment]
This has now been fixed as was seen on token.vega.xyz
