### ISSUE TITLE
Enacted proposal don't get updated on TFE

### ISSUE THREAD

**Issue by cpuja84** [vegaprotocol/token-frontend#790]
We are not publishing if the proposal once enacted, Token frontend doesn't tell you about this. Unsure if this is intensional, missed requirement or a bug

**Comment by cpuja84** [comment]
Design needs to show if votes is open, rejected, enacted. Should be shown on summary as well as details page.

**Comment by campbellssource** [comment]
For now we are just going to show open proposals. I'll create a new ticket for showing other statuses later
