### ISSUE TITLE
Voting updates across Console and Token UI not updating dynamically

### ISSUE THREAD

**Issue by cpuja84** [vegaprotocol/token-frontend#792]
Currently my votes or change of votes doesn't get transcended to both platforms. So basically if I vote or change my vote on Console, I need to refresh Token UI to see the change and vice versa. Ideally the vote / change of vote should be captured dynamically across both the platforms.

**Comment by campbellssource** [comment]
This to be covered in https://github.com/vegaprotocol/token-frontend/issues/1228
