### ISSUE TITLE
Version could not be found error received despite using the official Vega hosted wallet service on Testnet

### ISSUE THREAD

**Issue by cdm** [vegaprotocol/token-frontend#805]
Steps to reproduce:

* Open Chrome (or Safari) and goto incognito browser window (I've had same error without private browsing however)
* Tap Connect to see your Vega Key
* Fill out URL `https://wallet.testnet.vega.xyz`  (ps. Pleeeeeeease can we make this a selection on Testnet with Local Wallet vs Hosted Wallet? SO many people typing the url wrong or copying the URL they need for console which must have /api/v1 on the end 🤦 )
* Fill out correct hosted wallet details
* Login is successful
* In panel on right hand side gives the following error:

<img width="395" alt="Screenshot 2021-11-12 at 13 56 07" src="https://user-images.githubusercontent.com/149245/141479288-c17dbb6b-93fe-47fe-b769-cbcc45b0bba3.png">

**Comment by cdm** [comment]
Tested on a new hosted wallet account details below, NOTE I am NOT connected to an Ethereum wallet in my scenario above

user: cryptofail
pass: fail1

**Comment by cpuja84** [comment]
Able to connect to wallet without any issues in Chrome- incognito mode
