### ISSUE TITLE
Show Vega data ( e.g. validator list) without connection to Vega wallet.

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#820]
if not connect to Vega wallet:
- randomly select a node (see #297 for info)

When connected to a Vega wallet 
- use the node provided by the node

**Comment by dexturr** [comment]
This has been done as part of another ticket

**Comment by cpuja84** [comment]
We are showing Validator list without connecting to Vega Wallet

![Screenshot 2021-11-26 at 15 11 43](https://user-images.githubusercontent.com/69709857/143600924-aca296fb-b199-44bd-b4bf-03a7ff43badf.png)
