### ISSUE TITLE
Next Epoch field is missing when the first time nomination for a validator happens

### ISSUE THREAD

**Issue by cpuja84** [vegaprotocol/token-frontend#824]
There's some race condition in which Next Epoch Staking field acts weird for first time nomination.

**Scenario 1 -** 
1) Perform first time nomination on Validator 1 in epoch 1
2) Perform first time nomination on Validator 2 in epoch 1 ( same epoch as above)
Then Next Epoch Staking field for Validator 2 is missing from the balance bar, demonstrated by below screenshot

<img width="1349" alt="Screenshot 2021-11-15 at 14 54 29" src="https://user-images.githubusercontent.com/69709857/141866095-913eac00-454b-42f1-9011-c38a7c9d2f01.png">

**Scenario 2 -** 
1) Already have tokens staked on Validator 1 & 2
2) Perform more nominations on Validator 1 & 2 in epoch 3
3) Perform first time nomination on Validator 3 n epoch 3 ( same epoch as above)
Then Next Epoch Staking field for Validator 3 is missing from the balance bar, demonstrated by below screenshot

<img width="1179" alt="Screenshot 2021-11-15 at 14 56 03" src="https://user-images.githubusercontent.com/69709857/141866332-8eabd7d2-9bc4-433a-a963-9c0f8376f2c2.png">

**Comment by campbellssource** [comment]
This may have been fixed in the snags session today. https://github.com/vegaprotocol/token-frontend/tree/fix/misc
PR incoming.
Moving this to QA column to be retested on PR or after Merge

**Comment by cpuja84** [comment]
Issues with regards to first time nominations are resolved. Hence marking the story as done.
