### ISSUE TITLE
Update nomination message in “how much to add in next epoch” to refer to the network parameter

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#833]
The copy currently references a spam protection network parameter.
<img width="841" alt="Screenshot 2021-11-16 at 15 24 45" src="https://user-images.githubusercontent.com/13255539/142014019-66f6ddd1-e3d7-4d06-ac29-fa7ab403bcc2.png">
it should instead read this value and show it to the user.

> Your nomination must be greater than {{value}} $VEGA. This is a spam protection mechanism.

the network param is `spam.protection.delegation.min.tokens`

**Comment by campbellssource** [comment]
The rules have changed and this ticket is no-longer applicable.
You can nominate as much as you like, it will be added to the validator but you'll get a lower reward

**Comment by cpuja84** [comment]
The copy has been corrected to read - Your nomination must be greater than or equal to 0.1 $VEGA. And the genesis file for Staging has validators.delegation.minAmount = 0.1 Hence marking the story as done.

<img width="948" alt="Screenshot 2021-11-17 at 16 07 00" src="https://user-images.githubusercontent.com/69709857/142302416-4264926c-46b7-4e0f-8931-aed6d08210e8.png">
