### ISSUE TITLE
Bug: Styles missing on Vega wallet overlay form

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/token-frontend#843]
The inputs seem to have lost their styles

<img width="710" alt="Screen Shot 2021-11-16 at 4 57 23 PM" src="https://user-images.githubusercontent.com/6803987/142089932-fc8023c1-68b4-4672-9e5c-ecefa00f9d5e.png">

**Comment by cpuja84** [comment]
The styling of the vega wallet is now fixed
