### ISSUE TITLE
Staked Validator Table (sidebar) is jumping around

### ISSUE THREAD

**Issue by cpuja84** [vegaprotocol/token-frontend#847]
Make sure all the validators have staked tokens of different value with decimal places.
Observe the Vega Wallet Sidebar Screen.

Staked Validator List keeps changing dynamically

**Comment by campbellssource** [comment]
this happens only when validators do not have names and the amounts you have staked on each are the same. Will fix but have removed the critical label

**Comment by cpuja84** [comment]
The list of Staked Validators are no longer getting randomly sorted and is static throughout the epoch. This ticket could be closed.
