### ISSUE TITLE
No way to view history of withdrawals

### ISSUE THREAD

**Issue by cpuja84** [vegaprotocol/token-frontend#849]
- Incomplete Withdrawal Screen disappears from Withdraw Screen leaving user wondering about the completed withdrawals
- Incomplete withdrawal screen heading is misleading and should be better presented to user

**Comment by gordsport** [comment]
@mattrussell36 - will this be addressed in the reworking of the withdrawal forms?

If so I can add to the correct milestone to be tested

**Comment by gordsport** [comment]
- Add a link on /withdrawal
- to link to /withdrawals
