### ISSUE TITLE
copy change on nominating call out about amount might be different

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#858]
<img width="834" alt="Screenshot 2021-11-17 at 07 59 54" src="https://user-images.githubusercontent.com/13255539/142159578-265621b3-a1e8-437b-8248-0b77778670da.png">

currently says
>Adding 4 $VEGA to node Mutya*
> *Amount nominated may be less than intended
> This should take a few seconds to confirm, and then will be credited at the beginning of the next epoch

> Adding 4 $VEGA to node Mutya
> This should take a few seconds to confirm, and then will be credited at the beginning of the next epoch

AND

<img width="880" alt="Screenshot 2021-11-17 at 09 08 56" src="https://user-images.githubusercontent.com/13255539/142170766-c4a250ee-48f4-4880-8761-4098f498511d.png">

remove references to should. Only needs to remind you that it'll happen next epoch.

**Comment by candida-d** [comment]
Closed in https://github.com/vegaprotocol/token-frontend/pull/890

**Comment by cpuja84** [comment]
<img width="1296" alt="Screenshot 2021-11-18 at 15 26 06" src="https://user-images.githubusercontent.com/69709857/142512791-94e9a911-f405-45d2-8f39-4ff0f3cb907f.png">

<img width="1296" alt="Screenshot 2021-11-18 at 15 26 06" src="https://user-images.githubusercontent.com/69709857/142512806-b35df56b-67f3-4416-8f40-16833e1cee78.png">
