### ISSUE TITLE
Correct the delegation minimum amount

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#861]
following on from https://github.com/vegaprotocol/token-frontend/issues/833

**Comment by cpuja84** [comment]
The copy has been corrected to read - Your nomination must be greater than or equal to 0.1 $VEGA

<img width="948" alt="Screenshot 2021-11-17 at 16 07 00" src="https://user-images.githubusercontent.com/69709857/142302003-83078b1e-48b0-41fe-bca8-38197409430f.png">
