### ISSUE TITLE
Add an introduction to how rewards work on the withdraw page

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#863]
- should tell you about treasury
- and that your rewards are credited after x

**Comment by candida-d** [comment]
Closed with https://github.com/vegaprotocol/token-frontend/pull/890

**Comment by cpuja84** [comment]
Copy changes looks fine on Rewards and Withdrawal page

<img width="1453" alt="Screenshot 2021-11-18 at 15 40 59" src="https://user-images.githubusercontent.com/69709857/142514187-a38ac4cc-fe86-468f-afdf-a17967835ad6.png">

<img width="1417" alt="Screenshot 2021-11-18 at 15 41 57" src="https://user-images.githubusercontent.com/69709857/142514198-682650db-9130-43cd-aa0e-4a0f4ea42a3a.png">
