### ISSUE TITLE
Wallet sidebar: sticky + scrollable

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#864]
Problem: mobile
- Long sidebar will be cut off on mobile

![screenshot_2021-11-17_at_10 08 26](https://user-images.githubusercontent.com/13255539/142181715-78a3fc13-335d-4b40-bb62-f61287bc65df.png)

imperfection: desktop
- if the user has scrolled down the page to interact with the form, they may have also scrolled so that the side bar may not visible

Proposed solution.
The side bar should be held in a container that is fixed to the height of the viewport. (on mobile it is viewport - nav links). Meaning scrolling down the content area keeps the sidebar at top of viewport.
However the side bar content may be longer than the container so it also needs to be scrollble

**Comment by cpuja84** [comment]
The Wallet sidebar doesn't stick on Rewards Page. Please have a look 

https://user-images.githubusercontent.com/69709857/142295607-ad0b09cf-5500-45f4-af4b-28cf3fedd7a4.mov

1) Go to Withdrawal Tab and scroll to get to bottom of the page 
2) Return back to Rewards Tab by clicking on it and observe the screen

<img width="1083" alt="Screenshot 2021-11-17 at 14 54 54" src="https://user-images.githubusercontent.com/69709857/142295618-1ec68e11-54dc-4a45-98a0-8004a705ffae.png">

**Comment by dexturr** [comment]
This bug is raised as a seperate ticket yesterday #882, moving so this can be retested there. If this is the only issue can we move it to done?
