### ISSUE TITLE
Bug: Validator list alias alignment

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/token-frontend#876]
Alignment of alias and pubkey (possibly id) in validators list

**Comment by cpuja84** [comment]
The ID and Pub Key are aligned on Validator Staking page

<img width="1315" alt="Screenshot 2021-11-18 at 15 31 20" src="https://user-images.githubusercontent.com/69709857/142513171-038d9d4a-01ce-4b0a-af61-21ec4a0c6cf8.png">
