### ISSUE TITLE
Align version with change key and disconnect in vega wallet

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/token-frontend#880]
Per title

**Comment by cpuja84** [comment]
Version,  change key and disconnect in vega wallet are now aligned 

<img width="1296" alt="Screenshot 2021-11-18 at 15 26 06" src="https://user-images.githubusercontent.com/69709857/142513478-1e8b1c75-9425-48a5-8e14-65dc66c6b7f0.png">
