### ISSUE TITLE
Add useful links to footer

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/token-frontend#883]
<img width="1040" alt="Screenshot 2021-11-17 at 18 25 25" src="https://user-images.githubusercontent.com/13255539/142260024-95c42b5e-188c-49f0-84c2-8081ee27e709.png">

commit hash can link to `https://github.com/vegaprotocol/token-frontend/commit/[commit hash]`

`https://github.com/vegaprotocol/token-frontend/commit/61ec90a389cac584c2621d66c17d5e59e2ee372f`

Nolt: https://vega-testnet.nolt.io

Github: https://github.com/vegaprotocol/token-frontend

**Comment by cpuja84** [comment]
User is able to view the links on the footer section of the site on all the pages.

https://vega-testnet.nolt.io/

https://github.com/vegaprotocol/token-frontend

<img width="717" alt="Screenshot 2021-11-19 at 16 24 10" src="https://user-images.githubusercontent.com/69709857/142706909-778b624b-ca78-4366-b7d4-905381a13e67.png">
