### ISSUE TITLE
Change the Withdraw button to include $before VEGA Tokens

### ISSUE THREAD

**Issue by cpuja84** [vegaprotocol/token-frontend#893]
Everywhere else for CTA we refer $before VEGA Tokens but withdraw button doesn't. Would be ideal to get it fixed to be consistent with rest of the buttons.

<img width="887" alt="Screenshot 2021-11-17 at 12 45 24" src="https://user-images.githubusercontent.com/69709857/142279841-0957e41e-18dd-4bcc-a097-528b17ae532f.png">
<img width="928" alt="Screenshot 2021-11-17 at 12 23 56" src="https://user-images.githubusercontent.com/69709857/142279895-b2384f19-205b-4b3c-adf0-5c6407a913da.png">

**Comment by dexturr** [comment]
@campbellssource this is the symbol from the asset (from the API) should it
* remain as VEGA per the same design logic as the sidebar
* we get core to change the asset symbol to $VEGA
* we append a $ in front if the asset is VEGA

**Comment by campbellssource** [comment]
@cpuja84 is right to point out the inconsistency but I think it is just an exception to the general rule.
which is something like...
> In cases where a page or form only deals with VEGA tokens we should use all caps and Prepend a $ to make it distinct from the "Vega" network. But where a page or form shows or can show one of many assets Tether $USDT, DAI $DAI etc, the $ is superfluous.
I'm tempted to say let's use the asset name rather than symbol, but that is a justification hack. I'll make a comment in the design system to keep track of this, and define a 💪 policy

**Comment by cpuja84** [comment]
Thanks for the explanation @campbellssource. As long as we are tracking it one way or another I'm happy, will mark the story as done.
