### ISSUE TITLE
Token field doesn't get cleared when switching between Add and Remove Stake radio buttons

### ISSUE THREAD

**Issue by cpuja84** [vegaprotocol/token-frontend#894]
1) Stake some tokens to a validator.
2) Go to Manage your stake section. Select Add stake button and click Use Maximum.
3) Now select Remove button and observe the $VEGA Tokens text field.

Expected Result - The $VEGA Tokens text field gets cleared.

Actual Result - The $VEGA Tokens text field is prepopulated with token value from previous action of Adding stake

<img width="1057" alt="Screenshot 2021-11-17 at 14 35 39" src="https://user-images.githubusercontent.com/69709857/142293822-8f2f526c-9be1-43ad-9773-e11ea9b05ddc.png">
<img width="1144" alt="Screenshot 2021-11-17 at 14 35 45" src="https://user-images.githubusercontent.com/69709857/142293828-b9845357-d7e3-4767-945a-303827f454fe.png">

**Comment by dexturr** [comment]
This also doesn't happen on association between wallet/vesting contract. I think its fine due to max/in restraints, so you can't accidentally remove/add more than you have

**Comment by mattrussell36** [comment]
@campbellssource Is this worth doing before Staking v2?

**Comment by cpuja84** [comment]
@mattrussell36 - This is still broken on Staging https://staging.token.vega.xyz/staking


https://user-images.githubusercontent.com/69709857/144277492-0262aa3e-9854-410b-b121-192e7a71a034.mov

**Comment by cpuja84** [comment]
The bugfix works on Staging / Stagnet1
The value is getting cleared between Add and Removing Stake.
Signing off the ticket and marking on Done
