### ISSUE TITLE
Vega Wallet Balance is accurate only till one decimal place

### ISSUE THREAD

**Issue by cpuja84** [vegaprotocol/token-frontend#895]
1) Attempt to make a withdrawal and verify the Vega Wallet Balance. Its seems that the balance is not accurate.

In the example below I attempted to withdrawal 1 Vega Token. And below is the wallet balances before the withdrawal

<img width="522" alt="Screenshot 2021-11-17 at 17 11 44" src="https://user-images.githubusercontent.com/69709857/142333673-8ed256f0-1f37-4e78-862c-a4e421df803a.png">

I successfully complete both the levels of withdrawal process and now can see the Eth wallet balance incremented by 1.
Observe the Vega Wallet balance it becomes incorrect after one decimal place (10.3XXXXX).

Wallet balances after successful withdrawal

<img width="1406" alt="Screenshot 2021-11-17 at 17 16 55" src="https://user-images.githubusercontent.com/69709857/142333693-3a7cadb2-b8ac-4099-95c8-3679d596bf1e.png">

**Comment by dexturr** [comment]
@cpuja84 You sure that an epoch didn't pass between these two screen shots (incrementing your balance?)

**Comment by cpuja84** [comment]
This is working as expected. The epochs were changing which was generating rewards and crediting into the account.
