### ISSUE TITLE
Wallet sidebar: does not handle the wallet becoming disconnected very well

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#903]
Earlier I was connected to the front end with a running wallet.

I terminated my wallet in terminal

I get this.

<img width="593" alt="Screenshot 2021-11-18 at 19 42 31" src="https://user-images.githubusercontent.com/13255539/142485953-18bede93-ae16-4b0c-9da7-8a829752cbfa.png">

refresh doesn't help.

Expected:
back to the state where it shows a button to connect.

**Comment by campbellssource** [comment]
Closing this as the way it currently works is acceptable

**Comment by campbellssource** [comment]
Re-opening this as it looks like behaviour has changed and I can't get back into a state where I see the "Connect to Vega wallet" button

**Comment by mattrussell36** [comment]
@campbellssource Can you test again. I reverted some code which had broken how we fetch your wallet token.

See here: https://github.com/vegaprotocol/token-frontend/commit/50b2485972e4d32c5cd217767a6734496a187885

**Comment by campbellssource** [comment]
Yep Fixed, Thanks
