### ISSUE TITLE
Rewards view to clarify when reward will be available

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/token-frontend#907]
At the moment the rewards view shows reward per epoch with the lines:
- reward type,
- your stake,
- reward,
- share of reward.

I suggest adding another line which will show when the reward will be paid (or has been paid) into general account by checking the epoch end and payout delay. 

So for example if an epoch is ending 16th November 12:04 and payout delay is 72h then it will say: Reward will be transferred to general account 19th November 12:04.

**Comment by ze97286** [comment]
@davidsiska-vega No calculation is needed. The reward event has the *payout* time vs the calculation time.

**Comment by dexturr** [comment]
So the dates are broken on GQL `party.rewardsDetails.reward.recievedAt` at the moment (always shows 1/1/1970) and I have no property called payoutTime as it stands :cry:

I cannot use events as there is a problem with websockets on mainnet that i am working around :cry:

The best we can do to address this ticket short term is show the reward period. I could calculate the number of epochs per reward period take the current epoch start time and then calculate the date from there but this feels hacky and fragile. I spoke with @campbellssource and we are going to show the reward period in warning callout on the rewards page.

**Comment by ze97286** [comment]
@dexturr it's not called payoutTime, it's called receivedAt or whatever. In the version the validators have this is broken so currently in stagnet it will return 1/1/1970, but this was long fixed so whenever stagnet/testnet are deployed with current develop this will be reflected and GQL will return it correctly. 

If you want to calculate, you can just take the end time of the epoch matching the reward and add 72h to it.

**Comment by dexturr** [comment]
Sure, I'll create a follow up to add that once it is in thanks! 🙏

**Comment by cpuja84** [comment]
@dexturr @mattrussell36 @campbellssource - I can see the `reward.staking.delegation.payoutDelay` incorrectly published as 1 min for Staging as opposed to 15 min 

<img width="928" alt="Screenshot 2021-11-19 at 16 44 08" src="https://user-images.githubusercontent.com/69709857/142708014-508da457-d9fa-4a64-bddb-889474242e49.png">

**Comment by campbellssource** [comment]
@cpuja84 this one got a discussed a lot out side of there ticket.
In short the payout row was commented out by my request. I propose we wait till we have the number coming back correctly from core.

Also, I voted in a parameter change from 15m to 0m on Stagnet that's why it is not 15m as per the genesis file.
