### ISSUE TITLE
Help users debug issues connecting to wallet on localhost

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#915]
...by showing a message instead of the log in screen if the wallet service is not running.

Connecting to a Vega wallet is probably the 1 issue on discord

<img width="1027" alt="Screenshot 2021-11-30 at 14 39 46" src="https://user-images.githubusercontent.com/13255539/144067684-144f1bc5-4c20-41b2-a3a2-ce1be1c25eb8.png">

Background: At the moment you see this in the side bar when not connected

And when you click connect it open the modal.

<img width="622" alt="Screenshot 2021-11-30 at 13 52 39" src="https://user-images.githubusercontent.com/13255539/144059657-f8f6fd46-4f47-481b-9934-3f0dc3f33843.png">

And this if you attempt to connect but the site can't see the wallet running.

<img width="553" alt="Screenshot 2021-11-30 at 13 52 56" src="https://user-images.githubusercontent.com/13255539/144059880-5ee5a9f2-9e60-4a0b-bcda-b4ce831dfbf9.png">

Proposal:
When the Connect Vega wallet modal opens, check to see if the service is running.
if it isn't show a "No wallet detected on [wallet location address]"
as well as details to help them debug.

debug message 1: shown if the app/site is on https and the wallet location is http
> It is possible that your browser is preventing access to a wallet via http

debug message 2: shown when ever the service isn't detected
> The wallet service may not be running

- [x] include the "Get a Vega wallet" block (also used in side bar) that include link to guide and download.
- [x] Show one or both of the messages above if wallet not detected.
- [x] Do not show the rest of the form (username/password) if Wallet is not detected
- [x] Detect the wallet is running through appropriate end point
- [x] Poll to see if the wallet has stated since the message popped up, if it has render the form

**Comment by mattrussell36** [comment]
@campbellssource I think we can close this now with the latest changes to the vega wallet in the sidebar and the connect overlay?

**Comment by campbellssource** [comment]
@mattrussell36 No I think this one is still valid, but I'll add a design to ticket description to show what I mean...

**Comment by campbellssource** [comment]
@pgriscti to clarify the wallet location input shouldn't ever be disabled. as this allows the user to try another location for the wallet

**Comment by cpuja84** [comment]
This was tested and signed off on Stagnet 1 https://staging.token.vega.xyz/staking.

When Wallet service is not running on the machine then the user is prompted beforehand about no wallet services.

![Screenshot 2022-01-10 at 14 50 56](https://user-images.githubusercontent.com/69709857/148786381-c829da4f-d32a-4234-a2ee-9d95e675d5cc.png)

When Wallet services are running and user attempts to connect to Vega Wallet

![Screenshot 2022-01-10 at 14 50 41](https://user-images.githubusercontent.com/69709857/148786497-051bbd87-797c-4548-a5db-ce32f307b88a.png)
