### ISSUE TITLE
Add a link to get a vega wallet on the Associate page intro copy

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#916]
If a user clicks around too quickly they miss links to get a Vega wallet Wallet.
We should Ideally have a link to get a wallet everywhere there is a link to connect Vega wallet. But particularly priority is to add it to the /associate page as this is the first place you have to have it (the user could side step the button on the staking page with the new button in the side bar to associate)

see also : https://github.com/vegaprotocol/token-frontend/issues/919

which intends to be a landing page for people learning Vega wallet

**Comment by gordsport** [comment]
Link now available from the wallet side bar
