### ISSUE TITLE
We need to different sets of copy for the connect to x wallet button

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#917]
side bar should say 
...to associate $VEGA
and 
...to use associated $VEGA

but all in page buttons should just say
- Connect X wallet

**Comment by cpuja84** [comment]
We are now publishing consistent message about Connecting to Wallet on TFE.

<img width="1410" alt="Screenshot 2021-11-22 at 17 43 32" src="https://user-images.githubusercontent.com/69709857/142959825-0b61c025-bb6b-4580-a3ca-1e656f56e073.png">
