### ISSUE TITLE
Show Validator list without having to connect to a Vega wallet.

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#921]
At the moment the /Staking page will only show you a list of validators once you have connected to a Vega wallet.
it shouldn't instead, it should always show you the list.

**Comment by mattrussell36** [comment]
I presume we also want to allow people to click through to the validator page, but prevent staking of course.

**Comment by cpuja84** [comment]
We are now letting user browse the list of validator without having to connect to a wallet

<img width="1374" alt="Screenshot 2021-11-22 at 17 45 52" src="https://user-images.githubusercontent.com/69709857/142960025-60ca1db1-9f5f-4abc-a49f-03cd59ac399a.png">

Once they click on a validator then they are asked to connect to the wallet

<img width="1385" alt="Screenshot 2021-11-22 at 17 46 04" src="https://user-images.githubusercontent.com/69709857/142960053-43bd85e3-c265-4e16-9268-554a3b3531c7.png">
