### ISSUE TITLE
Possible caching issue resulting in UI flashing contradicting numbers

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/token-frontend#929]
From https://6196adb6fba4700008870dfc--token-vega-xyz.netlify.app/staking 

Apparently data nodes used are determined by https://github.com/vegaprotocol/token-frontend-api-proxy/blob/main/netlify.toml and according to @dexturr it's not that the UI is asking two different nodes getting two different answers. 

See the collateral amount on 
![image](https://user-images.githubusercontent.com/62546419/142733074-e61e92ce-94de-4427-a390-3d72c359e838.png)
 
versus the collateral amount on 
![image](https://user-images.githubusercontent.com/62546419/142733082-3f668d62-ad44-48f7-b846-758629fc4b93.png)

**Comment by cpuja84** [comment]
I haven't seen this happening in Staging so I ran a regression to ensure we haven't broken anything on Staking and looks like we haven't.
