### ISSUE TITLE
If we are using vote weight on open proposals we should remove vote summary as the data isn't there.

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#933]
summary on list page highlighted
<img width="876" alt="Screenshot 2021-11-22 at 13 22 29" src="https://user-images.githubusercontent.com/13255539/142869043-d3010998-e67d-47c4-86cc-9941ae91b564.png">

summary on vote page
<img width="862" alt="Screenshot 2021-11-22 at 13 23 18" src="https://user-images.githubusercontent.com/13255539/142869123-0d65c3b5-0fea-469a-9dbf-4a4cadf4d1ed.png">

**Comment by pgriscti** [comment]
We aren't using weight anywhere.

For this:
<img width="140" alt="Screenshot 2021-11-22 at 15 05 11" src="https://user-images.githubusercontent.com/7977128/142884886-a85a5007-636c-4e66-8a3f-93df1866afad.png">
we're doing: 
0.00%: `proposal.votes.no.totalTokens * 100 / (proposal.votes.no.totalTokens + proposal.votes.yes.totalTokens)`%
0: `proposal.votes.no.totalTokens`

**Comment by pgriscti** [comment]
participationMet = `(proposal.votes.no.totalTokens + proposal.votes.yes.totalTokens) > totalSupply * requiredParticipation`

**Comment by campbellssource** [comment]
okay. totalTokens isn't behaving the way we'd expect either. 
I say lets go ahead with removing all the vote summaries. (worth keeping this branch bookmarked for future use)

**Comment by cpuja84** [comment]
We have now removed the summary view from Update Network Governance Proposal detailed view

![Screenshot 2021-11-26 at 11 30 17](https://user-images.githubusercontent.com/69709857/143574631-cd73749c-2197-4148-9c52-491a003d4658.png)
