### ISSUE TITLE
Convert proposal subscriptions to use polling.

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/token-frontend#935]
Validators aren't set up to have websocket connections. So we need to revert to polling to detect when votes are submitted

**Comment by cpuja84** [comment]
I have performed a regression on Update Network Parameter Proposals and everything seems to be working ok

<img width="713" alt="Screenshot 2021-11-22 at 17 20 58" src="https://user-images.githubusercontent.com/69709857/142959339-53b678a7-4e58-47e2-bf3c-f5675d5e388a.png">
