### ISSUE TITLE
Bug: Stuck on Token FE loading screen

### ISSUE THREAD

**Issue by cdm** [vegaprotocol/token-frontend#937]
# Bug report

## Describe the bug

The Token FE is stuck on the initial loading screen and is failing to connect to a wss endpoint in the developer tools. Metamask keeps popping open and prompting user to re-authenticate. Authenticating with metamask (enter my password) cleared the loading and shows the Token FE correctly/immediately. Also had reports of getting stuck on loading screen when switching networks in MM.

## Environement

token.vega.xyz / chrome / macOSX

Had been previously logged in to metamask and token FE in same tab, around 24 hours ago.
## Expected behavior

To not be stuck at a loading screen but show me the Token FE with a need to connect to my Ethereum wallet etc.

## Screenshots

<img width="1430" alt="Screenshot 2021-11-22 at 20 15 32" src="https://user-images.githubusercontent.com/149245/142934473-5b686e76-39fa-4ea9-a5ad-6acfc63c2124.png">

<img width="357" alt="Screenshot 2021-11-22 at 20 25 52" src="https://user-images.githubusercontent.com/149245/142934488-7b833281-2a9e-4b42-b6df-be33afe0da54.png">

## Browser: 

You’re using Chrome 96.

## Additional context

Matt: "Basically the issue is that if you have previously connected, but then if Metamask requires permissions again we aren’t handling what happens if the user rejects MM at this point"

This thread 👉 https://vegaprotocol.slack.com/archives/C8WS7M50E/p1637612247356500

**Comment by cpuja84** [comment]
I left my TFE open overnight was on Governance tab and then moved to withdraw page and now see the chunk load errors   and a blank screen. I am unable to revive it without refreshing the page.
@mattrussell36 @campbellssource - Are we happy with this behavior as we no longer are getting websocket connection errors ? Please advise.

![Screenshot 2021-12-01 at 16 01 30](https://user-images.githubusercontent.com/69709857/144268971-8c8f73cc-8e90-4404-a981-ba9a7c79b380.png)

**Comment by dexturr** [comment]
I thought this bug was something else and so the PR reference above is not the fix. This still needs to be done. My bad!

**Comment by campbellssource** [comment]
Looks like there have been at least 2 different causes of this.
- 1 a release while a user has the site open
- memory leak
- ssl cors

Action: Test by leaving a tab open overnight

**Comment by campbellssource** [comment]
Closing this as it has not been seen for a while
