### ISSUE TITLE
Bug: voting fails / vote isn't shown in governance section

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/token-frontend#941]
# Bug report

## Describe the bug

I have voted on the mainnet governance proposal from key `3cd4768d73b97a90e23d4299d3ae647418c22848e1bd753a8a2e71e7c0b482a9`. This shows in the API but does not show in token front end. I am not sure if this is related to the fact that on refresh the TFE always seems to reset to the first key in the wallet and perhaps doesn't reload the vote info when switching keys?

## To Reproduce

Make a Vega wallet with more than 1 key
Swtich to the nth key where n > 1
Associate Vega tokens with the key
Go to governance
Vote for a proposal
Check the API to confirm the vote is counted
Check the proposal in the TFE to see your vote

## Expected behavior

TFE shows "You voted for" or "You voted against"

## Screenshots

<img width="822" alt="image" src="https://user-images.githubusercontent.com/1179257/142959059-d8f35eb8-b07d-49c8-bac0-befc1128e41a.png">

## Your browser information:

Chrome / Mac

## ETH Wallet software:

Frame.sh

## Vega Wallet software version:

Wallet version: v0.10.0
Pubkey: 3cd4768d73b97a90e23d4299d3ae647418c22848e1bd753a8a2e71e7c0b482a9

**Comment by campbellssource** [comment]
We believe this has been since fixed. QA to a re-test to ensure

**Comment by cpuja84** [comment]
This issue exists when I change my Vega Wallet Key from default, the vote doesn't get registered and persisted across for update network governance proposal.
Putting it back in TO DO list Column @campbellssource @pgriscti

**Comment by dexturr** [comment]
Related: #996

**Comment by cpuja84** [comment]
We are now rendering votes correctly for each public key. Switching across keys updates the vote correctly on Staging.
