### ISSUE TITLE
Feature request: make it easier to stake to multiple validators

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/token-frontend#956]
I worked out my staking in a spreadsheet and found the fact that you have to go through a flow for each validator rather than a single flow where I can enter amounts against all of them to be quite a chore.

Similarly to adjust the distribution I have to work out how much to remove from each and do they step by step then do the adds - again this could just be a “change stake” button or field per row that lets me edit many rows at once.

It should also tell me whether I’ve allocated everything in my staking account or gone over / got some left.

**Comment by campbellssource** [comment]
duplicate #758
