### ISSUE TITLE
Open proposal summary: using all the votes for and against

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#960]
bring back the vote summary and use the details on each pending vote to build up the total for/ against. These are not yet provided in API for open proposals.

**Comment by pgriscti** [comment]
show 2 decimal places

**Comment by pgriscti** [comment]
Participation: Not Met 0 <- no + yes
Participation: Not Met 0 0.0000% <- tokens votes percentage of total tokens fixed total supply 

query {
  assets {
    totalSupply
    name
  }
  
  
}

**Comment by cpuja84** [comment]
This has been done and signed off in Staging

![Screenshot 2021-12-03 at 17 09 20](https://user-images.githubusercontent.com/69709857/144643906-709f6da7-5f5d-4c9d-b952-863e9368b471.png)
