### ISSUE TITLE
Validators with a 0 balance (this and next) should not be show in the wallet sidebar.

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#962]
<img width="408" alt="Screenshot 2021-11-25 at 10 50 41" src="https://user-images.githubusercontent.com/13255539/143428287-2cee9aae-9c14-4d0a-ae4a-d7723484f4f3.png">

In this case Staking facilities did have a nomination from this user in a previous epoch.
issue: they appear in the list.
solution: they shouldn't

side note: Validators with 0 (rather than `null`) appear to get a this and next.

**Comment by cpuja84** [comment]
Hi @dexturr @campbellssource - I don't think this could be manually tested in Staging as this would be starting fresh on a validator node. Are we happy to have a look at this in Testnet if possible ?

![Screenshot 2021-11-30 at 16 58 12](https://user-images.githubusercontent.com/69709857/144092485-25ddd0d8-748e-4e01-aef9-92225cbd94b9.png)
