### ISSUE TITLE
Get the total supply from the assets query instead of the ethereum bridge

### ISSUE THREAD

**Issue by pgriscti** [vegaprotocol/token-frontend#967]
To be discussed within the team. 

`query {
  assets {
    totalSupply
    name
  }
}`

Ref: https://vegaprotocol.slack.com/archives/CD4AKTFQT/p1637935565322100

**Comment by mattrussell36** [comment]
https://supply.vega.xyz/total says 64999723 so whatever is returning the correct number we should just use that for now.

**Comment by dexturr** [comment]
Controversial opinion, I think the way we are doing it now is more correct
