### ISSUE TITLE
Use BigNumber for vote information calculations

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/token-frontend#971]
We are currently just using Number which could lead to some incorrect values.

**Comment by mattrussell36** [comment]
@cpuja84 Regression test on any vote information/values please! Its deployed on staging 2

**Comment by Ditmir-Vega** [comment]
Tested on Devnet  (dev.token.vega)

**Comment by cpuja84** [comment]
@Ditmir-Vega - Can we close this ticket then ?
