### ISSUE TITLE
Integration testing release 0.46.2 on stagnet2

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/token-frontend#983]
Core released 0.46.2 on stagnet2
Could we run some token UI manual tests to ensure no breaks on this release

Check for any automation tests we can run against stagnet2.

**Comment by cpuja84** [comment]
I have ran a sanity on the Token Front End and everything looks in order on Staging for release 0.46.2

**Comment by dexturr** [comment]
@cpuja84 Staging doesn't have 0.46.2 on it (for some reason this has skipped stagnet and gone straight to mainnet as can be seen https://stats.vega.trading)

You'll need to test this on testnet

![Screenshot 2021-11-30 at 16 42 46](https://user-images.githubusercontent.com/26136207/144089821-210a3f82-4298-4138-a441-f1a2148b1f5b.png)

**Comment by dexturr** [comment]
Rewards page is borked because of this :+1:
