### ISSUE TITLE
Withdrawals - Etherscan link points to ropsten even with mainnet

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/token-frontend#985]
Upon completing a withdrawal you get a link to etherscan: 
![image](https://user-images.githubusercontent.com/62546419/143910120-a1311efb-8a03-4467-9943-e89b737c45a5.png)

(bottom right). 

The transaction ID is valid but the link goes to ropsten even with mainnet.

**Comment by dexturr** [comment]
#977 adressed this, marking as closed :+1:
