### ISSUE TITLE
Make proposals on governance page more clearly indicate open/closed status

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/token-frontend#986]
Its not super clear which proposals are open vs closed in the proposals list.

Ref: https://vegaprotocol.slack.com/archives/C8W4JQ27P/p1638218365460600

**Comment by mattrussell36** [comment]
@campbellssource Any ideas on some quick wins here?

Initial thoughts:
- Don't show closed proposals, or hide them by default with a button to show
- More color usage to indicate active vs inactive proposals

**Comment by campbellssource** [comment]
will be fixed by new designs
