### ISSUE TITLE
Governance summary should include the simple Vote.status from api (on both listing and detail page

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#991]
On the listing page (/governance)
- Replace the line that shows... participation not met, etc with the Rejected, open etc form the API.

On the proposal details page (/governance/[proposalID])
- include a new row (first in the list) that shows the status from api `proposals.status`

## Colour coding (intent)
Failed - Red
Open - White
Passed - Green
Declined - Red
Rejected - Red
Enacted - Green
WaitingForNodeVote - White

**Comment by cpuja84** [comment]
I have seen the implementation of all the colour scheme but not all the proposal status on Staging and it looks ok to me. Hope that's ok @campbellssource.

![Screenshot 2021-12-03 at 13 51 11](https://user-images.githubusercontent.com/69709857/144613671-481dd757-592d-4fe8-9c99-6f5d17ff615b.png)
![Screenshot 2021-12-03 at 13 51 31](https://user-images.githubusercontent.com/69709857/144613676-415822ec-af28-42e3-bb55-5c0758a907f9.png)

@campbellssource- Are we happy with the field STATE  on the proposal details page ? Just checking if we wanted STATUS instead. Thanks !
![Screenshot 2021-12-03 at 13 52 07](https://user-images.githubusercontent.com/69709857/144613681-2890c013-9dde-463a-9707-3e10ce5eb408.png)

**Comment by campbellssource** [comment]
@cpuja84 yes happy in both cases.
we'll raise an issue if the other states are not the right colour
and state = the state of the proposal from the api `state` field
status = something we derive on the front end that attempts to sum up both participation and majority status.
☝️ rationale

**Comment by cpuja84** [comment]
Thanks @campbellssource, will mark this ticket as done.
