### ISSUE TITLE
Governance page, your vote status is not updated when switching keys

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#996]
To reproduce
got to /governance/[proposalID] 
with Vega key A, vote for.
switch to Vega key B... note that the status of your vote has not been update to the state of the new active key, but appears to be the state from the previous state

https://user-images.githubusercontent.com/13255539/144055745-0e32227f-c1f7-446d-9428-903acf9c1185.mov

In the video the key with the alias "fresh" voted against for the proposal but shows as against as that was the state of the other key

**Comment by dexturr** [comment]
Realted #941

**Comment by pgriscti** [comment]
Cannot create a new proposal ATM, so cannot test

**Comment by cpuja84** [comment]
Each key for a wallet has individual votes persistences and changing the keys across maintains their own votes rather than overriding with default key votes. Marking this story as done
